(()=>{
'use strict';
const SUPABASE_URL='https://cobuqvlfrufplefrkcgx.supabase.co';
const SUPABASE_KEY='sb_publishable_SKGz3p8xaze55as02_WVxA_P3KFoJO-';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const nowLabel=()=>new Intl.DateTimeFormat('es-MX',{hour:'numeric',minute:'2-digit',second:'2-digit'}).format(new Date());
let session=null,me=null,myPerms={},currentOwnerId=null,currentView='dashboard';
let profiles=[],permissions=[],shares=[],envelopes=[],accounts=[],ledger=[],fixedExpenses=[],cardPayments=[],financeSettings=[],cycleBudgets=[],savingsGoals=[],auditLogs=[];
let tempPasswords={},distributionContext=null;
const PERMS=[
 ['add_envelope','Crear apartados'],['delete_envelope','Eliminar apartados'],['rename_envelope','Editar apartados'],
 ['modify_amounts','Registrar/modificar importes'],['view_movements','Ver movimientos'],['generate_pdf','Generar PDF'],
 ['share_finances','Compartir finanzas'],['manage_accounts','Administrar cuentas/tarjetas'],['manage_fixed_expenses','Administrar pagos fijos']
];
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),3600)}
function apiError(err,fallback='Ocurrió un error'){console.error(err);toast(err?.message||fallback)}
function profile(id){return profiles.find(x=>x.id===id)}
function can(p){return me?.role==='admin'||myPerms?.[p]===true}
function accessibleOwners(){if(me?.role==='admin')return profiles.filter(p=>p.active);const ids=new Set([me.id,...shares.filter(s=>s.user_id===me.id).map(s=>s.owner_id)]);return profiles.filter(p=>ids.has(p.id)&&p.active)}
function owner(){return profile(currentOwnerId)}
function canWriteOwner(id){if(id===me?.id||me?.role==='admin')return true;return shares.some(s=>s.owner_id===id&&s.user_id===me.id&&s.permission==='write')}
function own(list){return list.filter(x=>x.owner_id===currentOwnerId)}
function ownerAccounts(){return own(accounts).filter(a=>a.active)}
function ownerEnvelopes(){return own(envelopes).filter(e=>e.active).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||a.name.localeCompare(b.name))}
function ownerLedger(){return own(ledger)}
function ownerFixed(){return own(fixedExpenses)}
function ownerCardPayments(){return own(cardPayments)}
function ownerGoals(){return own(savingsGoals).filter(g=>g.active)}
function ownerFinanceSetting(){return financeSettings.find(x=>x.owner_id===currentOwnerId)||{owner_id:currentOwnerId,pay_day:15,cycle_type:'monthly',anchor_pay_date:`${today().slice(0,8)}15`,budget_cycle_type:'monthly',budget_anchor_date:`${today().slice(0,8)}15`,business_mode:false,dashboard_sections:{apartados:true,fijos:true,movimientos:true,metas:true}}}
function parseISODate(v){const [y,m,d]=String(v||'').split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}
function dateISO(d){return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`}
function addDaysISO(v,days){const d=parseISODate(v);d.setUTCDate(d.getUTCDate()+days);return dateISO(d)}
function daysInMonthUTC(y,m){return new Date(Date.UTC(y,m+1,0)).getUTCDate()}
function monthlyDate(y,m,day){return `${y}-${pad(m+1)}-${pad(Math.min(day,daysInMonthUTC(y,m)))}`}
function cycleTypeLabel(t){return t==='weekly'?'Semanal':t==='biweekly'?'Quincenal':t==='variable'?'Ingreso variable':'Mensual'}
function periodBounds(ref,type,anchor){
 if(type==='weekly'||type==='biweekly'){
  const interval=type==='weekly'?7:15,rd=parseISODate(ref),ad=parseISODate(anchor),diff=Math.floor((rd-ad)/86400000),steps=Math.floor(diff/interval);
  const s=new Date(ad);s.setUTCDate(s.getUTCDate()+steps*interval);const n=new Date(s);n.setUTCDate(n.getUTCDate()+interval);const e=new Date(n);e.setUTCDate(e.getUTCDate()-1);
  return {start:dateISO(s),end:dateISO(e),nextCycle:dateISO(n),type};
 }
 const ad=parseISODate(anchor),day=ad.getUTCDate(),rd=parseISODate(ref),y=rd.getUTCFullYear(),m=rd.getUTCMonth();let start=monthlyDate(y,m,day);
 if(ref<start){let py=y,pm=m-1;if(pm<0){pm=11;py--}start=monthlyDate(py,pm,day)}
 const sd=parseISODate(start);let ny=sd.getUTCFullYear(),nm=sd.getUTCMonth()+1;if(nm>11){nm=0;ny++}const nextCycle=monthlyDate(ny,nm,day);
 return {start,end:addDaysISO(nextCycle,-1),nextCycle,type,payDay:day};
}
function cycleBounds(ref=today(),setting=null){
 const fs=setting||ownerFinanceSetting(),incomeType=['weekly','biweekly','monthly','variable'].includes(fs.cycle_type)?fs.cycle_type:'monthly',variable=incomeType==='variable';
 const type=variable?(['weekly','biweekly','monthly'].includes(fs.budget_cycle_type)?fs.budget_cycle_type:'monthly'):incomeType;
 const fallback=`${ref.slice(0,8)}${pad(Math.min(31,Math.max(1,Number(fs.pay_day)||15)))}`;
 const anchor=(variable?fs.budget_anchor_date:fs.anchor_pay_date)||fs.budget_anchor_date||fallback;
 return {...periodBounds(ref,type,anchor),incomeType,variable,nextPay:variable?null:periodBounds(ref,type,anchor).nextCycle};
}
function previousCycle(c){return cycleBounds(addDaysISO(c.start,-1))}
function accountTypeLabel(t){return t==='credit'?'Crédito':t==='debit'?'Débito':'Efectivo'}
function frequencyLabel(f){return f==='weekly'?'Semanal':f==='biweekly'?'Quincenal':f==='monthly'?'Mensual':'Una vez'}
function rolloverLabel(v){return v==='carry'?'Acumula sobrante':v==='keep'?'Conserva solo sobrante':'Reinicia al monto base'}
function accountBalance(a){
 const entries=ownerLedger().filter(e=>e.account_id===a.id),out=ownerCardPayments().filter(p=>p.source_account_id===a.id).reduce((s,p)=>s+Number(p.amount),0),inc=ownerCardPayments().filter(p=>p.credit_account_id===a.id).reduce((s,p)=>s+Number(p.amount),0);
 let v=Number(a.opening_balance)||0;
 for(const e of entries){const amt=Number(e.amount)||0;if(a.account_type==='credit'){if(e.entry_type==='expense')v+=amt;else if(e.entry_type==='income')v-=amt;else v+=amt*(Number(e.adjustment_direction)||1)}else{if(e.entry_type==='income')v+=amt;else if(e.entry_type==='expense')v-=amt;else v+=amt*(Number(e.adjustment_direction)||1)}}
 if(a.account_type==='credit')return Math.max(0,v-inc);return v-out;
}
function totalCash(){return ownerAccounts().filter(a=>a.account_type!=='credit').reduce((s,a)=>s+accountBalance(a),0)}
function totalDebt(){return ownerAccounts().filter(a=>a.account_type==='credit').reduce((s,a)=>s+accountBalance(a),0)}
function incomeInCycle(c){return ownerLedger().filter(x=>x.entry_type==='income'&&x.occurred_on>=c.start&&x.occurred_on<=c.end).reduce((s,x)=>s+Number(x.amount),0)}
function expensesInCycle(c){return ownerLedger().filter(x=>x.entry_type==='expense'&&x.occurred_on>=c.start&&x.occurred_on<=c.end).reduce((s,x)=>s+Number(x.amount),0)}
function businessNet(c){const list=ownerLedger().filter(x=>x.business_related&&x.occurred_on>=c.start&&x.occurred_on<=c.end);return list.reduce((s,x)=>s+(x.entry_type==='income'?Number(x.amount):x.entry_type==='expense'?-Number(x.amount):0),0)}
function spentForEnvelope(eid,from,to){return ownerLedger().filter(e=>e.entry_type==='expense'&&e.envelope_id===eid&&e.occurred_on>=from&&e.occurred_on<=to).reduce((s,e)=>s+Number(e.amount),0)}
function cycleBudgetOverride(e,c){return cycleBudgets.find(x=>x.envelope_id===e.id&&x.cycle_start===c.start)}
function envelopeBaseTarget(e,c){const ov=cycleBudgetOverride(e,c);if(ov)return Number(ov.reserved_amount)||0;if(Number(e.auto_percent)>0)return incomeInCycle(c)*(Number(e.auto_percent)/100);return Number(e.monthly_budget)||0}
function envelopeAvailableForCycle(e,c,depth=0){
 const base=envelopeBaseTarget(e,c),rule=e.rollover_rule||'reset';if(rule==='reset'||depth>24)return base;
 const created=String(e.created_at||'').slice(0,10);const p=previousCycle(c);if(created&&p.end<created)return base;
 const prevAvail=envelopeAvailableForCycle(e,p,depth+1),prevSpent=spentForEnvelope(e.id,p.start,p.end),left=Math.max(0,prevAvail-prevSpent);
 return rule==='carry'?base+left:left;
}
function envelopeRemaining(e,c=cycleBounds()){return Math.max(0,envelopeAvailableForCycle(e,c)-spentForEnvelope(e.id,c.start,c.end))}
function totalReserved(c=cycleBounds()){return ownerEnvelopes().reduce((s,e)=>s+envelopeRemaining(e,c),0)}
function goalReserved(){return ownerGoals().reduce((s,g)=>s+Number(g.saved_amount||0),0)}
function freeCash(c=cycleBounds()){return totalCash()-totalReserved(c)-goalReserved()}
function nextDue(date,freq){const d=parseISODate(date);if(freq==='weekly')d.setUTCDate(d.getUTCDate()+7);else if(freq==='biweekly')d.setUTCDate(d.getUTCDate()+15);else if(freq==='monthly')d.setUTCMonth(d.getUTCMonth()+1);else return null;return dateISO(d)}
function nextDayOfMonth(day,ref=today()){if(!day)return null;const d=parseISODate(ref),y=d.getUTCFullYear(),m=d.getUTCMonth();let v=monthlyDate(y,m,day);if(v<ref){let ny=y,nm=m+1;if(nm>11){nm=0;ny++}v=monthlyDate(ny,nm,day)}return v}
function cardStatementPeriod(a,ref=today()){if(!a.statement_day)return null;const d=parseISODate(ref),y=d.getUTCFullYear(),m=d.getUTCMonth(),cut=monthlyDate(y,m,a.statement_day);let start,end;if(ref>cut){start=addDaysISO(cut,1);let ny=y,nm=m+1;if(nm>11){nm=0;ny++}end=monthlyDate(ny,nm,a.statement_day)}else{let py=y,pm=m-1;if(pm<0){pm=11;py--}start=addDaysISO(monthlyDate(py,pm,a.statement_day),1);end=cut}return {start,end}}
function cardPeriodSpend(a){const p=cardStatementPeriod(a);if(!p)return 0;return ownerLedger().filter(x=>x.account_id===a.id&&x.entry_type==='expense'&&x.occurred_on>=p.start&&x.occurred_on<=today()).reduce((s,x)=>s+Number(x.amount),0)}
function fixedStatus(f){if(!f.active)return {label:'Inactivo',cls:'bad'};const c=cycleBounds();if(f.last_paid_on&&f.last_paid_on>=c.start&&f.last_paid_on<=c.end)return {label:'Pagado',cls:'good'};if(f.next_due_date<today())return {label:'Vencido',cls:'bad'};return {label:'Pendiente',cls:'warn'}}
async function loadAll(){
 const qs=[
  sb.from('profiles').select('*').order('full_name'),sb.from('user_permissions').select('*'),sb.from('shares').select('*').order('created_at'),
  sb.from('envelopes').select('*').order('created_at'),sb.from('accounts').select('*').order('created_at'),sb.from('ledger_entries').select('*').order('occurred_on',{ascending:false}),
  sb.from('fixed_expenses').select('*').order('next_due_date'),sb.from('card_payments').select('*').order('occurred_on',{ascending:false}),sb.from('finance_settings').select('*'),
  sb.from('envelope_cycle_budgets').select('*'),sb.from('savings_goals').select('*').order('created_at'),sb.from('audit_log').select('*').order('created_at',{ascending:false}).limit(200)
 ];
 const [p,up,s,e,a,l,f,cp,fs,cb,sg,al]=await Promise.all(qs);for(const r of [p,up,s,e,a,f,fs,cb,sg])if(r.error)throw r.error;
 profiles=p.data||[];permissions=up.data||[];shares=s.data||[];envelopes=e.data||[];accounts=a.data||[];ledger=l.error?[]:(l.data||[]);fixedExpenses=f.data||[];cardPayments=cp.error?[]:(cp.data||[]);financeSettings=fs.data||[];cycleBudgets=cb.data||[];savingsGoals=sg.data||[];auditLogs=al.error?[]:(al.data||[]);
 me=profile(session.user.id);myPerms=permissions.find(x=>x.user_id===session.user.id)||{};if(!me||!me.active)throw new Error('Usuario inactivo o sin perfil');if(!currentOwnerId||!accessibleOwners().some(x=>x.id===currentOwnerId))currentOwnerId=me.id;
 $('lastUpdated').textContent='Última actualización: '+nowLabel();
}
function refreshOwnerSelector(){const opts=accessibleOwners();$('ownerSelector').innerHTML=opts.map(o=>`<option value="${o.id}">${safe(o.full_name)}${me?.role==='admin'&&o.id!==me.id?' · '+safe(o.username):''}</option>`).join('');$('ownerSelector').value=currentOwnerId}
function updateCycleChip(){const c=cycleBounds();$('currentCycleChip').textContent=`${c.start} → ${c.end}`}
function setView(name){currentView=name;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('view-'+name).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));updateCycleChip();if(name==='dashboard')renderDashboard();if(name==='movimientos')renderMovements();if(name==='apartados')renderEnvelopes();if(name==='cuentas')renderAccounts();if(name==='fijos')renderFixed();if(name==='metas')renderGoals();if(name==='compartir')renderShares();if(name==='usuarios')renderUsers();if(name==='reporte')renderReport();if(name==='config')renderSettings()}
async function refreshData(showToast=true){const keep=currentOwnerId,view=currentView;await loadAll();if(accessibleOwners().some(x=>x.id===keep))currentOwnerId=keep;refreshOwnerSelector();setView(view);if(showToast)toast('Datos actualizados')}
function movementCard(t,withActions=true){
 const a=accounts.find(x=>x.id===t.account_id),e=envelopes.find(x=>x.id===t.envelope_id),label=t.entry_type==='income'?'Ingreso':t.entry_type==='expense'?'Gasto':'Ajuste',cls=t.entry_type==='income'?'good':t.entry_type==='expense'?'bad':'warn',write=canWriteOwner(currentOwnerId)&&can('modify_amounts');
 return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(t.comment||label)}</div><div class="small muted">${safe(t.occurred_on)} · ${safe(a?.name||'Cuenta')}${e?' · '+safe(e.name):''}${t.business_related?' · Negocio':''}</div></div><div class="right"><div class="amount ${cls}">${money(t.amount)}</div><span class="pill ${cls}">${a?.account_type==='credit'&&t.entry_type==='expense'?'Compra crédito':label}</span></div></div>${withActions?`<div class="row" style="margin-top:9px"><button class="btn secondary edit-movement" data-id="${t.id}" ${!write?'disabled':''}>Editar</button><button class="btn danger del-movement" data-id="${t.id}" ${!write?'disabled':''}>Eliminar</button></div>`:''}</div>`;
}
function fixedCard(f,actions=true){const st=fixedStatus(f),e=envelopes.find(x=>x.id===f.envelope_id),a=accounts.find(x=>x.id===f.preferred_account_id),write=canWriteOwner(currentOwnerId)&&can('manage_fixed_expenses');return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(f.name)}</div><div class="small muted">${frequencyLabel(f.frequency)} · vence ${safe(f.next_due_date)}${f.variable_amount?' · monto variable':''}${e?' · '+safe(e.name):''}${a?' · '+safe(a.name):''}</div>${f.last_paid_on?`<div class="small muted">Último pago: ${safe(f.last_paid_on)}</div>`:''}</div><div class="right"><div class="amount">${money(f.amount)}</div><span class="pill ${st.cls}">${st.label}</span></div></div>${actions?`<div class="row" style="margin-top:9px"><button class="btn primary pay-fixed" data-id="${f.id}" ${!write||!f.active?'disabled':''}>Pagar</button><button class="btn secondary edit-fixed" data-id="${f.id}" ${!write?'disabled':''}>Editar</button><button class="btn ghost toggle-fixed" data-id="${f.id}" ${!write?'disabled':''}>${f.active?'Desactivar':'Activar'}</button></div>`:''}</div>`}
function goalCard(g,actions=true){const pct=Math.min(100,(Number(g.saved_amount)/Number(g.target_amount))*100),write=canWriteOwner(currentOwnerId)&&can('modify_amounts');return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(g.name)}</div><div class="small muted">Meta ${money(g.target_amount)}${g.deadline?' · '+safe(g.deadline):''}</div></div><div class="right"><div class="goal-amount">${money(g.saved_amount)}</div><div class="small muted">Faltan ${money(Math.max(0,Number(g.target_amount)-Number(g.saved_amount)))}</div></div></div><div class="progress" style="margin-top:9px"><span style="width:${pct}%"></span></div>${actions?`<div class="row" style="margin-top:9px"><button class="btn primary adjust-goal" data-id="${g.id}" ${!write?'disabled':''}>Aportar / retirar</button><button class="btn secondary edit-goal" data-id="${g.id}" ${!write?'disabled':''}>Editar</button><button class="btn ghost toggle-goal" data-id="${g.id}" ${!write?'disabled':''}>Desactivar</button></div>`:''}</div>`}
function renderDashboard(){
 refreshOwnerSelector();const o=owner();if(!o)return;const c=cycleBounds(),fs=ownerFinanceSetting(),reserved=totalReserved(c),goals=goalReserved(),cash=totalCash(),free=freeCash(c),prefs=fs.dashboard_sections||{};
 $('dashOwnerName').textContent=o.full_name;$('dashCash').textContent=money(free);$('dashCycle').textContent=`Ciclo ${c.start} al ${c.end}${c.variable?' · ingreso variable':''}`;$('dashBalanceDetail').textContent=`Saldo real ${money(cash)} · Apartados ${money(reserved)} · Metas ${money(goals)}`;
 $('statIncome').textContent=money(incomeInCycle(c));$('statExpense').textContent=money(expensesInCycle(c));$('statReserved').textContent=money(reserved+goals);$('statCreditDebt').textContent=money(totalDebt());$('statBusinessCard').classList.toggle('hidden',!fs.business_mode);$('statBusiness').textContent=money(businessNet(c));
 if(me.role==='admin'&&o.id!==me.id){$('adminModeNote').textContent=`Modo administrador: puedes ver y modificar las finanzas de ${o.full_name} (${o.username}).`;$('adminModeNote').classList.remove('hidden')}else $('adminModeNote').classList.add('hidden');
 $('dashCardApartados').classList.toggle('hidden',prefs.apartados===false);$('dashCardFijos').classList.toggle('hidden',prefs.fijos===false);$('dashCardMovs').classList.toggle('hidden',prefs.movimientos===false);$('dashCardMetas').classList.toggle('hidden',prefs.metas===false);
 const env=ownerEnvelopes();$('dashBars').innerHTML=env.length?env.map(e=>{const avail=envelopeAvailableForCycle(e,c),spent=spentForEnvelope(e.id,c.start,c.end),remain=Math.max(0,avail-spent),pct=avail?Math.min(100,spent/avail*100):0;return `<div class="barrow"><span>${safe(e.name)}</span><div class="bar"><span style="width:${pct}%"></span></div><b>${money(remain)}</b></div>`}).join(''):'<div class="empty">Aún no hay apartados.</div>';
 $('dashGoals').innerHTML=ownerGoals().length?ownerGoals().slice(0,4).map(g=>goalCard(g,false)).join(''):'<div class="empty">No hay metas activas.</div>';
 const f=ownerFixed().filter(x=>x.active).sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date)).slice(0,5);$('dashFixed').innerHTML=f.length?f.map(x=>fixedCard(x,false)).join(''):'<div class="empty">No hay pagos fijos pendientes.</div>';
 const recent=[...ownerLedger()].sort((a,b)=>(b.occurred_on+b.created_at).localeCompare(a.occurred_on+a.created_at)).slice(0,6);$('recentList').innerHTML=recent.length?recent.map(x=>movementCard(x,false)).join(''):'<div class="empty">No hay movimientos todavía.</div>';
}
function fillMovementSelectors(){const type=$('movementType').value,list=ownerAccounts().filter(a=>type==='income'?a.account_type!=='credit':true);$('movementAccount').innerHTML=list.map(a=>`<option value="${a.id}">${safe(a.name)} · ${accountTypeLabel(a.account_type)}</option>`).join('');$('movementEnvelope').innerHTML='<option value="">Sin apartado</option>'+ownerEnvelopes().map(e=>`<option value="${e.id}">${safe(e.name)}</option>`).join('');$('movementEnvelopeField').classList.toggle('hidden',type==='income')}
function fillMovementFilters(){const av=$('filterAccount').value,ev=$('filterEnvelope').value;$('filterAccount').innerHTML='<option value="">Todas</option>'+ownerAccounts().map(a=>`<option value="${a.id}">${safe(a.name)}</option>`).join('');$('filterEnvelope').innerHTML='<option value="">Todos</option>'+ownerEnvelopes().map(e=>`<option value="${e.id}">${safe(e.name)}</option>`).join('');$('filterAccount').value=av;$('filterEnvelope').value=ev}
function renderMovements(){
 const write=canWriteOwner(currentOwnerId)&&can('modify_amounts');$('newIncomeBtn').disabled=!write;$('newExpenseBtn').disabled=!write;fillMovementFilters();if(!$('filterFrom').value||!$('filterTo').value){const c=cycleBounds();$('filterFrom').value=c.start;$('filterTo').value=c.end}
 let tx=[...ownerLedger()].sort((a,b)=>(b.occurred_on+b.created_at).localeCompare(a.occurred_on+a.created_at));const q=$('filterText').value.trim().toLowerCase(),type=$('filterType').value,acc=$('filterAccount').value,env=$('filterEnvelope').value,from=$('filterFrom').value,to=$('filterTo').value;if(q)tx=tx.filter(x=>(x.comment||'').toLowerCase().includes(q));if(type)tx=tx.filter(x=>x.entry_type===type);if(acc)tx=tx.filter(x=>x.account_id===acc);if(env)tx=tx.filter(x=>x.envelope_id===env);if(from)tx=tx.filter(x=>x.occurred_on>=from);if(to)tx=tx.filter(x=>x.occurred_on<=to);
 $('movementList').innerHTML=!can('view_movements')?'<div class="note">No tienes permiso para visualizar movimientos.</div>':tx.length?tx.map(x=>movementCard(x,true)).join(''):'<div class="empty">No hay movimientos con esos filtros.</div>';document.querySelectorAll('.edit-movement').forEach(b=>b.onclick=()=>editMovement(b.dataset.id));document.querySelectorAll('.del-movement').forEach(b=>b.onclick=()=>deleteMovement(b.dataset.id));
}
function openMovement(type,fixed=null){if(!canWriteOwner(currentOwnerId)||!can('modify_amounts'))return toast('No tienes permiso para registrar movimientos');$('movementId').value='';$('movementFixedId').value=fixed?.id||'';$('movementType').disabled=false;$('movementType').value=type;$('movementDate').value=today();$('movementAmount').value=fixed?fixed.amount:'';$('movementComment').value=fixed?fixed.name:'';$('movementBusiness').checked=!!ownerFinanceSetting().business_mode;$('movementFormTitle').textContent=fixed?'Pagar '+fixed.name:(type==='income'?'Registrar ingreso':'Registrar gasto');fillMovementSelectors();if(fixed){if(fixed.preferred_account_id)$('movementAccount').value=fixed.preferred_account_id;$('movementEnvelope').value=fixed.envelope_id||''}$('businessRelatedWrap').classList.toggle('hidden',!ownerFinanceSetting().business_mode);$('movementFormCard').classList.remove('hidden');setView('movimientos');window.scrollTo({top:0,behavior:'smooth'})}
function editMovement(id){const t=ledger.find(x=>x.id===id);if(!t)return;$('movementId').value=t.id;$('movementFixedId').value=t.fixed_expense_id||'';$('movementType').value=t.entry_type;$('movementType').disabled=true;$('movementDate').value=t.occurred_on;$('movementAmount').value=t.amount;$('movementComment').value=t.comment||'';$('movementBusiness').checked=!!t.business_related;$('movementFormTitle').textContent='Editar movimiento';fillMovementSelectors();$('movementAccount').value=t.account_id;$('movementEnvelope').value=t.envelope_id||'';$('businessRelatedWrap').classList.toggle('hidden',!ownerFinanceSetting().business_mode);$('movementFormCard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function deleteMovement(id){if(!confirm('¿Eliminar este movimiento? El saldo y los apartados se recalcularán automáticamente.'))return;const {error}=await sb.from('ledger_entries').delete().eq('id',id);if(error)return apiError(error);await refreshData(false);setView('movimientos');toast('Movimiento eliminado')}
function openDistribution(income){const c=cycleBounds(income.occurred_on);distributionContext={income,cycle:c};$('distributionInfo').textContent=`Ingreso ${money(income.amount)} del ${income.occurred_on}. Define cuánto quieres reservar en cada apartado para el ciclo ${c.start} al ${c.end}.`;$('distributionRows').innerHTML=ownerEnvelopes().map(e=>`<label class="distribution-row"><span>${safe(e.name)}${Number(e.auto_percent)>0?` · ${Number(e.auto_percent)}% automático`:''}</span><input class="dist-amount" data-id="${e.id}" type="number" min="0" step="0.01" value="${envelopeAvailableForCycle(e,c).toFixed(2)}"></label>`).join('')||'<div class="empty">No hay apartados para distribuir.</div>';$('distributionCard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function saveDistribution(){if(!distributionContext)return;const {income,cycle}=distributionContext,rows=[...document.querySelectorAll('.dist-amount')];for(const input of rows){const e=envelopes.find(x=>x.id===input.dataset.id),amount=Math.max(0,Number(input.value)||0);const payload={owner_id:currentOwnerId,envelope_id:e.id,cycle_start:cycle.start,cycle_end:cycle.end,reserved_amount:amount,created_by:me.id,note:`Distribución del ingreso ${income.id}`};const {error}=await sb.from('envelope_cycle_budgets').upsert(payload,{onConflict:'envelope_id,cycle_start'});if(error)return apiError(error)}distributionContext=null;$('distributionCard').classList.add('hidden');await refreshData(false);setView('dashboard');toast('Distribución guardada')}
function fillEnvelopeSources(){const v=$('envelopeSource').value;$('envelopeSource').innerHTML='<option value="">Sin cuenta específica</option>'+ownerAccounts().filter(a=>a.account_type!=='credit').map(a=>`<option value="${a.id}">${safe(a.name)}</option>`).join('');$('envelopeSource').value=v}
function renderEnvelopes(){
 const c=cycleBounds(),write=canWriteOwner(currentOwnerId);$('newEnvelopeBtn').disabled=!(write&&can('add_envelope'));const list=ownerEnvelopes();$('envelopeList').innerHTML=list.length?list.map(e=>{const avail=envelopeAvailableForCycle(e,c),spent=spentForEnvelope(e.id,c.start,c.end),remain=Math.max(0,avail-spent),src=accounts.find(a=>a.id===e.source_account_id);return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(e.name)}</div><div class="small muted">Base ${money(e.monthly_budget)}${Number(e.auto_percent)>0?` · ${Number(e.auto_percent)}% de ingresos`:''} · ${rolloverLabel(e.rollover_rule)}${src?' · '+safe(src.name):''}</div></div><div class="right"><div class="amount ${remain<=0?'bad':'good'}">${money(remain)}</div><div class="small muted">Reservado ${money(avail)} · Gastado ${money(spent)}</div></div></div><div class="row" style="margin-top:9px"><button class="btn secondary edit-env" data-id="${e.id}" ${!(write&&can('rename_envelope'))?'disabled':''}>Editar</button><button class="btn danger del-env" data-id="${e.id}" ${!(write&&can('delete_envelope'))?'disabled':''}>Eliminar</button></div></div>`}).join(''):'<div class="empty">No hay apartados.</div>';document.querySelectorAll('.edit-env').forEach(b=>b.onclick=()=>editEnvelope(b.dataset.id));document.querySelectorAll('.del-env').forEach(b=>b.onclick=()=>deleteEnvelope(b.dataset.id));
 const debts=ownerAccounts().filter(a=>a.account_type==='credit');$('envelopeDebtList').innerHTML=debts.length?debts.map(a=>`<div class="item"><div class="row between"><div><div class="item-title">${safe(a.name)}</div><div class="small muted">Deuda inicial ${money(a.opening_balance)}${a.opening_note?' · '+safe(a.opening_note):' · Sin motivo registrado'}</div></div><div class="right"><div class="amount warn">Debes ${money(accountBalance(a))}</div><div class="small muted">Límite ${money(a.credit_limit)}</div></div></div><div class="row" style="margin-top:9px"><button class="btn secondary edit-debt-account" data-id="${a.id}">Editar deuda / tarjeta</button></div></div>`).join(''):'<div class="empty">No hay tarjetas de crédito activas.</div>';document.querySelectorAll('.edit-debt-account').forEach(b=>b.onclick=()=>{setView('cuentas');editAccount(b.dataset.id)});
}
function editEnvelope(id){const e=envelopes.find(x=>x.id===id);if(!e)return;fillEnvelopeSources();$('envelopeId').value=e.id;$('envelopeName').value=e.name;$('envelopeBudget').value=e.monthly_budget||0;$('envelopePercent').value=e.auto_percent||0;$('envelopeSource').value=e.source_account_id||'';$('envelopeRollover').value=e.rollover_rule||'reset';$('envelopeFormTitle').textContent='Editar apartado';$('envelopeFormCard').classList.remove('hidden')}
async function deleteEnvelope(id){if(!confirm('¿Eliminar este apartado? Los movimientos históricos conservarán la referencia mientras la base lo permita.'))return;const {error}=await sb.from('envelopes').delete().eq('id',id);if(error)return apiError(error);await refreshData(false);setView('apartados');toast('Apartado eliminado')}
function accountTypeUI(){const credit=$('accountType').value==='credit';$('creditFields').classList.toggle('hidden',!credit);$('openingLabel').textContent=credit?'Deuda inicial':'Saldo inicial';$('openingNoteLabel').textContent=credit?'Motivo / detalle de deuda inicial':'Nota del saldo inicial';$('accountOpeningNote').placeholder=credit?'Ej. Compra anterior, saldo transferido...':'Ej. Saldo que ya tenía la cuenta'}
function openAccountCreate(){if(!canWriteOwner(currentOwnerId)||!can('manage_accounts'))return toast('No tienes permiso');$('accountId').value='';$('accountName').value='';$('accountType').disabled=false;$('accountType').value='debit';$('accountOpening').value='0';$('accountLimit').value='0';$('accountStatementDay').value='';$('accountDueDay').value='';$('accountMinimumPayment').value='0';$('accountNoInterestPayment').value='0';$('accountOpeningNote').value='';$('accountTypeHint').textContent='';$('accountFormTitle').textContent='Nueva cuenta / tarjeta';accountTypeUI();$('accountFormCard').classList.remove('hidden')}
function editAccount(id){const a=accounts.find(x=>x.id===id);if(!a)return;$('accountId').value=a.id;$('accountName').value=a.name;$('accountType').value=a.account_type;const hasHistory=ledger.some(x=>x.account_id===a.id)||cardPayments.some(x=>x.source_account_id===a.id||x.credit_account_id===a.id);$('accountType').disabled=hasHistory;$('accountTypeHint').textContent=hasHistory?'El tipo no puede cambiar porque ya tiene movimientos.':'';$('accountOpening').value=a.opening_balance||0;$('accountLimit').value=a.credit_limit||0;$('accountStatementDay').value=a.statement_day||'';$('accountDueDay').value=a.due_day||'';$('accountMinimumPayment').value=a.minimum_payment||0;$('accountNoInterestPayment').value=a.no_interest_payment||0;$('accountOpeningNote').value=a.opening_note||'';$('accountFormTitle').textContent='Editar cuenta / tarjeta';accountTypeUI();$('accountFormCard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function renderAccounts(){
 const write=canWriteOwner(currentOwnerId)&&can('manage_accounts');$('newAccountBtn').disabled=!write;const list=own(accounts);$('accountList').innerHTML=list.length?list.map(a=>{const v=accountBalance(a),credit=a.account_type==='credit',avail=credit?Math.max(0,Number(a.credit_limit||0)-v):null,p=credit?cardStatementPeriod(a):null;return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(a.name)}</div><div class="small muted">${accountTypeLabel(a.account_type)} · ${credit?'Deuda':'Saldo'} inicial ${money(a.opening_balance)}</div>${a.opening_note?`<div class="small muted">${safe(a.opening_note)}</div>`:''}${credit&&p?`<div class="small muted">Periodo tarjeta ${p.start} → ${p.end} · Compras periodo ${money(cardPeriodSpend(a))}</div>`:''}${credit&&a.due_day?`<div class="small muted">Próximo límite de pago ${nextDayOfMonth(a.due_day)}</div>`:''}</div><div class="right"><div class="amount ${credit?'warn':v<0?'bad':'good'}">${credit?'Debes '+money(v):money(v)}</div>${credit?`<div class="small muted">Crédito disponible ${money(avail)}</div>`:''}</div></div>${credit?`<div class="mini-grid" style="margin-top:9px"><div class="muted-box"><div class="small muted">Pago mínimo</div><b>${money(a.minimum_payment)}</b></div><div class="muted-box"><div class="small muted">Para no generar intereses</div><b>${money(a.no_interest_payment)}</b></div></div>`:''}<div class="row" style="margin-top:9px"><span class="pill ${a.active?'good':'bad'}">${a.active?'Activa':'Inactiva'}</span><button class="btn secondary edit-account" data-id="${a.id}" ${!write?'disabled':''}>Editar</button>${credit&&a.active?`<button class="btn blue pay-card" data-id="${a.id}" ${!can('modify_amounts')?'disabled':''}>Pagar tarjeta</button>`:''}<button class="btn ghost toggle-account" data-id="${a.id}" ${!write?'disabled':''}>${a.active?'Desactivar':'Activar'}</button></div></div>`}).join(''):'<div class="empty">No hay cuentas ni tarjetas.</div>';document.querySelectorAll('.edit-account').forEach(b=>b.onclick=()=>editAccount(b.dataset.id));document.querySelectorAll('.pay-card').forEach(b=>b.onclick=()=>openCardPayment(b.dataset.id));document.querySelectorAll('.toggle-account').forEach(b=>b.onclick=()=>toggleAccount(b.dataset.id));
}
async function toggleAccount(id){const a=accounts.find(x=>x.id===id);if(!a)return;const {error}=await sb.from('accounts').update({active:!a.active}).eq('id',id);if(error)return apiError(error);await refreshData(false);setView('cuentas')}
function openCardPayment(id){const a=accounts.find(x=>x.id===id),sources=ownerAccounts().filter(x=>x.account_type!=='credit');if(!a||!sources.length)return toast('Necesitas una cuenta de débito o efectivo para pagar');$('paymentCreditId').value=a.id;$('paymentCreditName').value=a.name;$('paymentSource').innerHTML=sources.map(x=>`<option value="${x.id}">${safe(x.name)} · ${money(accountBalance(x))}</option>`).join('');$('paymentAmount').value=a.no_interest_payment>0?a.no_interest_payment:'';$('paymentDate').value=today();$('paymentComment').value='';$('paymentFormCard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function fillFixedSelectors(){const ev=$('fixedEnvelope').value,av=$('fixedAccount').value;$('fixedEnvelope').innerHTML='<option value="">Sin apartado</option>'+ownerEnvelopes().map(e=>`<option value="${e.id}">${safe(e.name)}</option>`).join('');$('fixedAccount').innerHTML='<option value="">Elegir al pagar</option>'+ownerAccounts().map(a=>`<option value="${a.id}">${safe(a.name)} · ${accountTypeLabel(a.account_type)}</option>`).join('');$('fixedEnvelope').value=ev;$('fixedAccount').value=av}
function renderFixed(){const write=canWriteOwner(currentOwnerId)&&can('manage_fixed_expenses');$('newFixedBtn').disabled=!write;const list=[...own(fixedExpenses)].sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date));$('fixedList').innerHTML=list.length?list.map(f=>fixedCard(f,true)).join(''):'<div class="empty">No hay pagos fijos.</div>';document.querySelectorAll('.pay-fixed').forEach(b=>b.onclick=()=>{const f=fixedExpenses.find(x=>x.id===b.dataset.id);openMovement('expense',f)});document.querySelectorAll('.edit-fixed').forEach(b=>b.onclick=()=>editFixed(b.dataset.id));document.querySelectorAll('.toggle-fixed').forEach(b=>b.onclick=()=>toggleFixed(b.dataset.id))}
function editFixed(id){const f=fixedExpenses.find(x=>x.id===id);if(!f)return;fillFixedSelectors();$('fixedId').value=f.id;$('fixedName').value=f.name;$('fixedAmount').value=f.amount;$('fixedFrequency').value=f.frequency;$('fixedVariable').checked=!!f.variable_amount;$('fixedDue').value=f.next_due_date;$('fixedEnvelope').value=f.envelope_id||'';$('fixedAccount').value=f.preferred_account_id||'';$('fixedFormTitle').textContent='Editar pago fijo';$('fixedFormCard').classList.remove('hidden')}
async function toggleFixed(id){const f=fixedExpenses.find(x=>x.id===id);if(!f)return;const {error}=await sb.from('fixed_expenses').update({active:!f.active}).eq('id',id);if(error)return apiError(error);await refreshData(false);setView('fijos')}
function fillGoalSources(){const v=$('goalSource').value;$('goalSource').innerHTML='<option value="">Sin cuenta específica</option>'+ownerAccounts().filter(a=>a.account_type!=='credit').map(a=>`<option value="${a.id}">${safe(a.name)}</option>`).join('');$('goalSource').value=v}
function renderGoals(){const write=canWriteOwner(currentOwnerId)&&can('modify_amounts');$('newGoalBtn').disabled=!write;const list=own(savingsGoals);$('goalList').innerHTML=list.length?list.map(g=>g.active?goalCard(g,true):`<div class="item"><div class="row between"><div><div class="item-title">${safe(g.name)}</div><div class="small muted">Inactiva · ${money(g.saved_amount)} ahorrado</div></div><button class="btn ghost toggle-goal" data-id="${g.id}" ${!write?'disabled':''}>Activar</button></div></div>`).join(''):'<div class="empty">No hay metas de ahorro.</div>';document.querySelectorAll('.adjust-goal').forEach(b=>b.onclick=()=>openGoalAdjust(b.dataset.id));document.querySelectorAll('.edit-goal').forEach(b=>b.onclick=()=>editGoal(b.dataset.id));document.querySelectorAll('.toggle-goal').forEach(b=>b.onclick=()=>toggleGoal(b.dataset.id))}
function editGoal(id){const g=savingsGoals.find(x=>x.id===id);if(!g)return;fillGoalSources();$('goalId').value=g.id;$('goalName').value=g.name;$('goalTarget').value=g.target_amount;$('goalSaved').value=g.saved_amount;$('goalSource').value=g.source_account_id||'';$('goalDeadline').value=g.deadline||'';$('goalFormTitle').textContent='Editar meta';$('goalFormCard').classList.remove('hidden')}
function openGoalAdjust(id){const g=savingsGoals.find(x=>x.id===id);if(!g)return;$('goalAdjustId').value=id;$('goalAdjustAmount').value='';$('goalAdjustTitle').textContent='Ajustar '+g.name;$('goalAdjustCard').classList.remove('hidden')}
async function adjustGoal(direction){const g=savingsGoals.find(x=>x.id===$('goalAdjustId').value),amt=Number($('goalAdjustAmount').value);if(!g||!(amt>0))return toast('Indica un monto');if(direction>0&&amt>freeCash())return toast('El monto supera tu disponible libre');const saved=Math.max(0,Number(g.saved_amount)+direction*amt);const {error}=await sb.from('savings_goals').update({saved_amount:saved}).eq('id',g.id);if(error)return apiError(error);$('goalAdjustCard').classList.add('hidden');await refreshData(false);setView('metas');toast(direction>0?'Aportación registrada':'Retiro registrado')}
async function toggleGoal(id){const g=savingsGoals.find(x=>x.id===id);const {error}=await sb.from('savings_goals').update({active:!g.active}).eq('id',id);if(error)return apiError(error);await refreshData(false);setView('metas')}
function renderShares(){const others=profiles.filter(u=>u.active&&u.id!==me.id);$('shareUser').innerHTML=others.map(u=>`<option value="${u.id}">${safe(u.full_name)} (${safe(u.username)})</option>`).join('');$('shareForm').querySelector('button').disabled=!can('share_finances')||currentOwnerId!==me.id;const mine=shares.filter(s=>s.owner_id===me.id);$('shareList').innerHTML=mine.length?mine.map(s=>{const u=profile(s.user_id);return `<div class="item"><div class="row between"><div><div class="item-title">${safe(u?.full_name||'Usuario')}</div><div class="small muted">${safe(u?.username||'')}</div></div><span class="pill ${s.permission==='write'?'blue':''}">${s.permission==='write'?'Lectura y escritura':'Solo lectura'}</span></div><button class="btn danger revoke-share" data-id="${s.id}" style="margin-top:9px">Quitar acceso</button></div>`}).join(''):'<div class="empty">No has compartido tus finanzas.</div>';document.querySelectorAll('.revoke-share').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('shares').delete().eq('id',b.dataset.id);if(error)return apiError(error);await refreshData(false);setView('compartir')})}
function renderPermissionChecks(){$('permissionChecks').innerHTML=PERMS.map(([k,l])=>`<label class="checkbox-row"><input type="checkbox" data-perm="${k}" checked> ${l}</label>`).join('')}
async function refreshUsersDirectory(show=false){await loadAll();refreshOwnerSelector();renderUsers();if(show)toast('Usuarios actualizados')}
function renderUsers(){if(me.role!=='admin')return;$('userList').innerHTML=profiles.map(u=>{const visible=tempPasswords[u.id];return `<div class="item"><div class="row between"><div><div class="item-title">${safe(u.full_name)}</div><div class="small muted">${u.role==='admin'?'Administrador':'Usuario'} · ${safe(u.username)}</div></div><span class="pill ${u.active?'good':'bad'}">${u.active?'Activo':'Inactivo'}</span></div><div class="credential-box"><div class="credential-line"><span>Usuario</span><code>${safe(u.username)}</code></div><div class="credential-line"><span>Contraseña</span>${visible?`<code>${safe(visible)}</code>`:'<span class="protected">Protegida por Supabase</span>'}</div></div><div class="row" style="margin-top:9px">${u.active?`<button class="btn primary view-user-finances" data-id="${u.id}">Ver / administrar finanzas</button>`:''}${u.id!==me.id?`<button class="btn secondary toggle-user" data-id="${u.id}">${u.active?'Desactivar':'Activar'}</button><button class="btn ghost perms-user" data-id="${u.id}">Permisos</button><button class="btn ghost reset-pass" data-id="${u.id}">Nueva contraseña</button>`:'<span class="small muted">Tu contraseña se cambia en Ajustes.</span>'}</div></div>`}).join('');document.querySelectorAll('.view-user-finances').forEach(b=>b.onclick=()=>{currentOwnerId=b.dataset.id;refreshOwnerSelector();setView('dashboard');toast('Administrando finanzas de '+(profile(b.dataset.id)?.full_name||'usuario'))});document.querySelectorAll('.toggle-user').forEach(b=>b.onclick=async()=>{const u=profile(b.dataset.id);const {error}=await sb.from('profiles').update({active:!u.active}).eq('id',u.id);if(error)return apiError(error);await refreshUsersDirectory()});document.querySelectorAll('.perms-user').forEach(b=>b.onclick=()=>editPermissions(b.dataset.id));document.querySelectorAll('.reset-pass').forEach(b=>b.onclick=()=>resetPassword(b.dataset.id))}
async function editPermissions(id){const u=profile(id),p=permissions.find(x=>x.user_id===id)||{};if(!u)return;const current=PERMS.map(([k,l])=>`${l}: ${p[k]?'Sí':'No'}`).join('\n');const choice=prompt(`Permisos actuales de ${u.full_name}:\n\n${current}\n\nEscribe TODO para habilitar todos o NINGUNO para deshabilitar todos.`);if(choice===null)return;const v=choice.trim().toUpperCase();if(!['TODO','NINGUNO'].includes(v))return toast('Sin cambios');const update=Object.fromEntries(PERMS.map(([k])=>[k,v==='TODO']));const {error}=await sb.from('user_permissions').update(update).eq('user_id',id);if(error)return apiError(error);await refreshUsersDirectory();toast('Permisos actualizados')}
function makeTempPassword(){const b=new Uint32Array(2);crypto.getRandomValues(b);return `MiDinero-${b[0].toString(36)}${b[1].toString(36)}`.slice(0,20)}
async function resetPassword(id){const u=profile(id),suggested=makeTempPassword(),password=prompt(`Nueva contraseña temporal para ${u.full_name}:`,suggested);if(password===null)return;if(password.length<8)return toast('Mínimo 8 caracteres');const {data,error}=await sb.functions.invoke('reset-user-password',{body:{user_id:id,password}});if(error)return apiError(error);if(data?.error)return toast(data.error);tempPasswords[id]=password;renderUsers();toast('Contraseña temporal actualizada')}
function reportEvents(){
 const state=Object.fromEntries(own(accounts).map(a=>[a.id,Number(a.opening_balance)||0])),events=[];ownerLedger().forEach(t=>events.push({date:t.occurred_on,created:t.created_at||'',kind:'ledger',data:t}));ownerCardPayments().forEach(p=>events.push({date:p.occurred_on,created:p.created_at||'',kind:'card',data:p}));events.sort((a,b)=>(a.date+a.created).localeCompare(b.date+b.created));const rows=[];
 for(const ev of events){if(ev.kind==='ledger'){const t=ev.data,a=accounts.find(x=>x.id===t.account_id),before=state[t.account_id]??0,amt=Number(t.amount),credit=a?.account_type==='credit';let after=before;if(credit){if(t.entry_type==='expense')after+=amt;else if(t.entry_type==='income')after=Math.max(0,after-amt);else after=Math.max(0,after+amt*(Number(t.adjustment_direction)||1))}else{if(t.entry_type==='income')after+=amt;else if(t.entry_type==='expense')after-=amt;else after+=amt*(Number(t.adjustment_direction)||1)}state[t.account_id]=after;rows.push({id:t.id,date:t.occurred_on,created_at:t.created_at,updated_at:t.updated_at,type:t.entry_type==='income'?'Ingreso':t.entry_type==='expense'?'Gasto':'Ajuste',account:a?.name||'',envelope:envelopes.find(e=>e.id===t.envelope_id)?.name||'',amount:amt,before,after,creator:profile(t.created_by)?.full_name||'',comment:t.comment||'',fixed:fixedExpenses.find(f=>f.id===t.fixed_expense_id)?.name||'',business:!!t.business_related})}else{const p=ev.data,s=accounts.find(a=>a.id===p.source_account_id),cr=accounts.find(a=>a.id===p.credit_account_id),amt=Number(p.amount),bs=state[p.source_account_id]??0,bc=state[p.credit_account_id]??0,as=bs-amt,ac=Math.max(0,bc-amt);state[p.source_account_id]=as;state[p.credit_account_id]=ac;rows.push({id:p.id,date:p.occurred_on,created_at:p.created_at,updated_at:p.updated_at,type:'Pago tarjeta',account:`${s?.name||''} → ${cr?.name||''}`,envelope:'',amount:amt,before:`${money(bs)} / deuda ${money(bc)}`,after:`${money(as)} / deuda ${money(ac)}`,creator:profile(p.created_by)?.full_name||'',comment:p.comment||'',fixed:'',business:false})}}
 return rows;
}
function fillReportCycles(){const old=$('reportCyclePreset').value,opts=[];let c=cycleBounds();for(let i=0;i<12;i++){opts.push(c);c=previousCycle(c)}$('reportCyclePreset').innerHTML=opts.map((x,i)=>`<option value="${x.start}|${x.end}">${i===0?'Ciclo actual':'Ciclo anterior '+i}: ${x.start} → ${x.end}</option>`).join('')+'<option value="custom">Personalizado</option>';if(old&&[...$('reportCyclePreset').options].some(o=>o.value===old))$('reportCyclePreset').value=old;else $('reportCyclePreset').selectedIndex=0}
function renderReport(){
 fillReportCycles();if(!$('reportFrom').value||!$('reportTo').value){const c=cycleBounds();$('reportFrom').value=c.start;$('reportTo').value=c.end}const from=$('reportFrom').value,to=$('reportTo').value,rows=reportEvents().filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));$('reportOwnerName').textContent=owner()?.full_name||'';$('reportPeriodText').textContent=`${from||'Inicio'} → ${to||'Hoy'}`;const income=rows.filter(r=>r.type==='Ingreso').reduce((s,r)=>s+r.amount,0),expense=rows.filter(r=>r.type==='Gasto').reduce((s,r)=>s+r.amount,0),pays=rows.filter(r=>r.type==='Pago tarjeta').reduce((s,r)=>s+r.amount,0),biz=rows.filter(r=>r.business).reduce((s,r)=>s+(r.type==='Ingreso'?r.amount:r.type==='Gasto'?-r.amount:0),0),c=cycleBounds(to||today());$('reportIncome').textContent=money(income);$('reportExpense').textContent=money(expense);$('reportReserved').textContent=money(totalReserved(c)+goalReserved());$('reportCardPayments').textContent=money(pays);$('reportDebt').textContent=money(totalDebt());$('reportBusinessCard').classList.toggle('hidden',!ownerFinanceSetting().business_mode);$('reportBusiness').textContent=money(biz);$('printBtn').disabled=!can('generate_pdf');$('exportCsvBtn').disabled=!can('generate_pdf');$('reportBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${safe(r.date)}</td><td><span class="nowrap">${safe((r.created_at||'').replace('T',' ').slice(0,16))}</span>${r.updated_at&&r.updated_at!==r.created_at?`<br><span class="small muted">Mod. ${safe(r.updated_at.replace('T',' ').slice(0,16))}</span>`:''}</td><td>${safe(r.type)}</td><td>${safe(r.account)}</td><td>${safe(r.envelope)}</td><td>${money(r.amount)}</td><td>${typeof r.before==='number'?money(r.before):safe(r.before)}</td><td>${typeof r.after==='number'?money(r.after):safe(r.after)}</td><td>${safe(r.creator)}</td><td>${safe(r.comment)}${r.fixed?` · Pago fijo: ${safe(r.fixed)}`:''}${r.business?' · Negocio':''}</td></tr>`).join(''):'<tr><td colspan="10">Sin movimientos.</td></tr>';renderAudit();
}
function renderAudit(){const show=me.role==='admin';$('auditCard').classList.toggle('hidden',!show);if(!show)return;const rows=auditLogs.filter(x=>x.owner_id===currentOwnerId).slice(0,30);$('auditList').innerHTML=rows.length?rows.map(x=>{const actor=profile(x.actor_id);return `<div class="audit-line"><b>${safe(actor?.full_name||'Sistema')}</b> · ${safe(x.action)} ${safe(x.entity_type)} · ${new Date(x.created_at).toLocaleString('es-MX')}</div>`}).join(''):'<div class="empty">No hay cambios registrados.</div>'}
function csvCell(v){const s=String(v??'').replace(/"/g,'""');return `"${s}"`}
function exportCSV(){const from=$('reportFrom').value,to=$('reportTo').value,o=owner(),rows=reportEvents().filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));const headers=['Propietario','Periodo','Fecha','Creado','Última modificación','Tipo','Cuenta/Tarjeta','Apartado','Monto','Saldo/Deuda anterior','Saldo/Deuda posterior','Pago fijo','Usuario registró','Negocio','Concepto','ID'];const lines=[headers,...rows.map(r=>[o?.full_name||'',`${from} a ${to}`,r.date,r.created_at||'',r.updated_at||'',r.type,r.account,r.envelope,r.amount,typeof r.before==='number'?r.before:r.before,typeof r.after==='number'?r.after:r.after,r.fixed,r.creator,r.business?'Sí':'No',r.comment,r.id])].map(row=>row.map(csvCell).join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Mi_Dinero_${(o?.username||'usuario')}_${from}_${to}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function renderSettings(){const fs=ownerFinanceSetting(),o=owner(),editable=o&&(o.id===me.id||me.role==='admin');$('cycleOwnerLabel').textContent=`Configuración de ${o?.full_name||''}`;$('cycleType').value=fs.cycle_type||'monthly';$('anchorPayDate').value=fs.anchor_pay_date||'';$('budgetCycleType').value=fs.budget_cycle_type||'monthly';$('budgetAnchorDate').value=fs.budget_anchor_date||'';$('businessMode').checked=!!fs.business_mode;updateCycleSettingsUI();const p=fs.dashboard_sections||{};$('dashShowApartados').checked=p.apartados!==false;$('dashShowMetas').checked=p.metas!==false;$('dashShowFijos').checked=p.fijos!==false;$('dashShowMovs').checked=p.movimientos!==false;$('cycleForm').querySelector('button[type="submit"]').disabled=!editable;$('saveDashboardPrefsBtn').disabled=!editable}
function updateCycleSettingsUI(){const variable=$('cycleType').value==='variable';$('payDateField').classList.toggle('hidden',variable);$('variableBudgetFields').classList.toggle('hidden',!variable);updateCyclePreview()}
function updateCyclePreview(){const fs=ownerFinanceSetting(),type=$('cycleType').value,variable=type==='variable',anchor=variable?$('budgetAnchorDate').value:$('anchorPayDate').value,btype=variable?$('budgetCycleType').value:type;if(!anchor){$('cyclePreview').textContent=variable?'Selecciona el ciclo y fecha de referencia.':'Selecciona una fecha de pago.';return}const p=periodBounds(today(),btype,anchor);$('cyclePreview').textContent=variable?`Ingresos sin fecha fija. Apartados/gastos: ${p.start} al ${p.end}.`:`Ciclo actual: ${p.start} al ${p.end}. Próximo pago: ${p.nextCycle}.`}
async function renderApp(){await loadAll();$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('whoName').textContent=me.full_name;$('whoRole').textContent=me.role==='admin'?'Administrador':'Usuario';refreshOwnerSelector();renderPermissionChecks();const nav=document.querySelector('.nav-inner');if(me.role==='admin'&&!document.querySelector('[data-view="usuarios"]')){const b=document.createElement('button');b.dataset.view='usuarios';b.innerHTML='<span class="ico">♟</span>Usuarios';b.onclick=()=>setView('usuarios');nav.insertBefore(b,nav.lastElementChild)}setView('dashboard')}

$('loginForm').onsubmit=async e=>{e.preventDefault();const username=$('loginUser').value.trim().toLowerCase(),password=$('loginPass').value;if(!/^[a-z0-9._-]{3,32}$/.test(username))return toast('Usuario inválido');const res=await sb.auth.signInWithPassword({email:username+'@midinero.local',password});if(res.error)return apiError(res.error,'Usuario o contraseña incorrectos');session=res.data.session;currentOwnerId=session.user.id;try{await renderApp()}catch(err){apiError(err)}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refreshDataBtn').onclick=()=>refreshData(true).catch(apiError);document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('ownerSelector').onchange=()=>{currentOwnerId=$('ownerSelector').value;distributionContext=null;$('distributionCard').classList.add('hidden');setView('dashboard')};
$('quickIncome').onclick=()=>openMovement('income');$('quickExpense').onclick=()=>openMovement('expense');$('quickAccount').onclick=()=>{setView('cuentas');openAccountCreate()};$('quickFixed').onclick=()=>{setView('fijos');$('newFixedBtn').click()};
$('newIncomeBtn').onclick=()=>openMovement('income');$('newExpenseBtn').onclick=()=>openMovement('expense');$('cancelMovementBtn').onclick=()=>{$('movementFormCard').classList.add('hidden');$('movementType').disabled=false};$('movementType').onchange=fillMovementSelectors;
$('movementForm').onsubmit=async e=>{e.preventDefault();const id=$('movementId').value,type=$('movementType').value,accountId=$('movementAccount').value,amount=Number($('movementAmount').value),fixedId=$('movementFixedId').value||null;if(!(amount>0)||!accountId)return toast('Completa monto y cuenta');const existing=id?ledger.find(x=>x.id===id):null;const payload={owner_id:currentOwnerId,account_id:accountId,envelope_id:type==='expense'?($('movementEnvelope').value||null):null,fixed_expense_id:fixedId,created_by:existing?.created_by||me.id,entry_type:type,amount,comment:$('movementComment').value.trim(),occurred_on:$('movementDate').value||today(),adjustment_direction:null,business_related:$('movementBusiness').checked};const targetAccount=accounts.find(a=>a.id===accountId);if(type==='expense'&&targetAccount?.account_type==='credit'&&Number(targetAccount.credit_limit)>0){const existingAmt=existing&&existing.account_id===accountId&&existing.entry_type==='expense'?Number(existing.amount):0;if(accountBalance(targetAccount)-existingAmt+amount>Number(targetAccount.credit_limit))return toast('Este gasto supera el límite de crédito disponible');}let result;if(id)result=await sb.from('ledger_entries').update(payload).eq('id',id).select().single();else result=await sb.from('ledger_entries').insert(payload).select().single();if(result.error)return apiError(result.error);if(!id&&fixedId){const f=fixedExpenses.find(x=>x.id===fixedId),n=nextDue(payload.occurred_on,f.frequency),update={last_paid_on:payload.occurred_on};if(n)update.next_due_date=n;else update.active=false;await sb.from('fixed_expenses').update(update).eq('id',fixedId)}$('movementFormCard').classList.add('hidden');$('movementType').disabled=false;await loadAll();refreshOwnerSelector();setView('movimientos');if(!id&&type==='income'&&ownerEnvelopes().length)openDistribution(result.data);else toast(id?'Movimiento actualizado':type==='income'?'Ingreso registrado':'Gasto registrado')};
['filterText','filterType','filterAccount','filterEnvelope','filterFrom','filterTo'].forEach(id=>$(id).addEventListener(id==='filterText'?'input':'change',renderMovements));$('saveDistributionBtn').onclick=saveDistribution;$('skipDistributionBtn').onclick=()=>{$('distributionCard').classList.add('hidden');distributionContext=null;toast('Ingreso registrado sin cambiar distribución')};
$('newEnvelopeBtn').onclick=()=>{fillEnvelopeSources();$('envelopeId').value='';$('envelopeName').value='';$('envelopeBudget').value='0';$('envelopePercent').value='0';$('envelopeSource').value='';$('envelopeRollover').value='reset';$('envelopeFormTitle').textContent='Nuevo apartado';$('envelopeFormCard').classList.remove('hidden')};$('cancelEnvelopeBtn').onclick=()=>$('envelopeFormCard').classList.add('hidden');$('envelopeForm').onsubmit=async e=>{e.preventDefault();const id=$('envelopeId').value,payload={owner_id:currentOwnerId,name:$('envelopeName').value.trim(),monthly_budget:Math.max(0,Number($('envelopeBudget').value)||0),auto_percent:Math.max(0,Math.min(100,Number($('envelopePercent').value)||0)),source_account_id:$('envelopeSource').value||null,rollover_rule:$('envelopeRollover').value,initial_balance:0,current_balance:0};if(!payload.name)return;const r=id?await sb.from('envelopes').update(payload).eq('id',id):await sb.from('envelopes').insert(payload);if(r.error)return apiError(r.error);$('envelopeFormCard').classList.add('hidden');await refreshData(false);setView('apartados');toast('Apartado guardado')};
$('newAccountBtn').onclick=openAccountCreate;$('cancelAccountBtn').onclick=()=>{$('accountFormCard').classList.add('hidden');$('accountType').disabled=false};$('accountType').onchange=accountTypeUI;$('accountForm').onsubmit=async e=>{e.preventDefault();const id=$('accountId').value,existing=id?accounts.find(x=>x.id===id):null,type=$('accountType').disabled&&existing?existing.account_type:$('accountType').value,payload={owner_id:currentOwnerId,name:$('accountName').value.trim(),account_type:type,opening_balance:Math.max(0,Number($('accountOpening').value)||0),credit_limit:type==='credit'?Math.max(0,Number($('accountLimit').value)||0):null,opening_note:$('accountOpeningNote').value.trim(),statement_day:type==='credit'?(Number($('accountStatementDay').value)||null):null,due_day:type==='credit'?(Number($('accountDueDay').value)||null):null,minimum_payment:type==='credit'?Math.max(0,Number($('accountMinimumPayment').value)||0):0,no_interest_payment:type==='credit'?Math.max(0,Number($('accountNoInterestPayment').value)||0):0};if(!payload.name)return;const r=id?await sb.from('accounts').update(payload).eq('id',id):await sb.from('accounts').insert(payload);if(r.error)return apiError(r.error);$('accountFormCard').classList.add('hidden');$('accountType').disabled=false;await refreshData(false);setView('cuentas');toast(id?'Cuenta actualizada':'Cuenta agregada')};
$('cancelPaymentBtn').onclick=()=>$('paymentFormCard').classList.add('hidden');$('paymentForm').onsubmit=async e=>{e.preventDefault();const amount=Number($('paymentAmount').value),creditId=$('paymentCreditId').value,source=$('paymentSource').value;if(!(amount>0)||!source||!creditId)return;const sourceAcc=accounts.find(a=>a.id===source),creditAcc=accounts.find(a=>a.id===creditId);if(sourceAcc&&amount>accountBalance(sourceAcc))return toast('El pago supera el saldo disponible de la cuenta origen');if(creditAcc&&amount>accountBalance(creditAcc))return toast('El pago supera la deuda actual de la tarjeta');const {error}=await sb.from('card_payments').insert({owner_id:currentOwnerId,source_account_id:source,credit_account_id:creditId,created_by:me.id,amount,comment:$('paymentComment').value.trim(),occurred_on:$('paymentDate').value||today()});if(error)return apiError(error);$('paymentFormCard').classList.add('hidden');await refreshData(false);setView('cuentas');toast('Pago a tarjeta registrado')};
$('newFixedBtn').onclick=()=>{fillFixedSelectors();$('fixedId').value='';$('fixedName').value='';$('fixedAmount').value='';$('fixedFrequency').value='monthly';$('fixedVariable').checked=false;$('fixedDue').value=today();$('fixedEnvelope').value='';$('fixedAccount').value='';$('fixedFormTitle').textContent='Nuevo pago fijo';$('fixedFormCard').classList.remove('hidden')};$('cancelFixedBtn').onclick=()=>$('fixedFormCard').classList.add('hidden');$('fixedForm').onsubmit=async e=>{e.preventDefault();const id=$('fixedId').value,payload={owner_id:currentOwnerId,name:$('fixedName').value.trim(),amount:Number($('fixedAmount').value),frequency:$('fixedFrequency').value,next_due_date:$('fixedDue').value,envelope_id:$('fixedEnvelope').value||null,preferred_account_id:$('fixedAccount').value||null,active:true,variable_amount:$('fixedVariable').checked};if(!payload.name||!(payload.amount>0)||!payload.next_due_date)return toast('Completa los datos');const r=id?await sb.from('fixed_expenses').update(payload).eq('id',id):await sb.from('fixed_expenses').insert(payload);if(r.error)return apiError(r.error);$('fixedFormCard').classList.add('hidden');await refreshData(false);setView('fijos');toast('Pago fijo guardado')};
$('newGoalBtn').onclick=()=>{fillGoalSources();$('goalId').value='';$('goalName').value='';$('goalTarget').value='';$('goalSaved').value='0';$('goalSource').value='';$('goalDeadline').value='';$('goalFormTitle').textContent='Nueva meta';$('goalFormCard').classList.remove('hidden')};$('cancelGoalBtn').onclick=()=>$('goalFormCard').classList.add('hidden');$('goalForm').onsubmit=async e=>{e.preventDefault();const id=$('goalId').value,payload={owner_id:currentOwnerId,name:$('goalName').value.trim(),target_amount:Number($('goalTarget').value),saved_amount:Math.max(0,Number($('goalSaved').value)||0),source_account_id:$('goalSource').value||null,deadline:$('goalDeadline').value||null,active:true};if(!payload.name||!(payload.target_amount>0))return toast('Completa la meta');const r=id?await sb.from('savings_goals').update(payload).eq('id',id):await sb.from('savings_goals').insert(payload);if(r.error)return apiError(r.error);$('goalFormCard').classList.add('hidden');await refreshData(false);setView('metas');toast('Meta guardada')};$('goalAddBtn').onclick=()=>adjustGoal(1);$('goalWithdrawBtn').onclick=()=>adjustGoal(-1);$('cancelGoalAdjustBtn').onclick=()=>$('goalAdjustCard').classList.add('hidden');
$('shareForm').onsubmit=async e=>{e.preventDefault();const userId=$('shareUser').value;if(!userId)return;const permission=$('sharePermission').value,existing=shares.find(s=>s.owner_id===me.id&&s.user_id===userId);const r=existing?await sb.from('shares').update({permission}).eq('id',existing.id):await sb.from('shares').insert({owner_id:me.id,user_id:userId,permission});if(r.error)return apiError(r.error);await refreshData(false);setView('compartir');toast('Finanzas compartidas')};
$('refreshUsersBtn').onclick=()=>refreshUsersDirectory(true).catch(apiError);$('newUserBtn').onclick=()=>$('userFormCard').classList.remove('hidden');$('cancelUserBtn').onclick=()=>$('userFormCard').classList.add('hidden');$('userForm').onsubmit=async e=>{e.preventDefault();const username=$('userUsername').value.trim().toLowerCase(),password=$('userPassword').value,full_name=$('userFullname').value.trim(),role=$('userRole').value;if(!/^[a-z0-9._-]{3,32}$/.test(username))return toast('Usuario inválido');if(password.length<8)return toast('Mínimo 8 caracteres');const perms={};document.querySelectorAll('[data-perm]').forEach(c=>perms[c.dataset.perm]=c.checked);const {data,error}=await sb.functions.invoke('create-user',{body:{username,password,full_name,permissions:perms}});if(error)return apiError(error);const id=data?.user_id;if(id){tempPasswords[id]=password;await sb.from('profiles').update({role}).eq('id',id);await sb.from('user_permissions').update(perms).eq('user_id',id)}$('userForm').reset();renderPermissionChecks();$('userFormCard').classList.add('hidden');await refreshUsersDirectory();toast('Usuario creado')};
$('reportCyclePreset').onchange=()=>{const v=$('reportCyclePreset').value;if(v!=='custom'){const [a,b]=v.split('|');$('reportFrom').value=a;$('reportTo').value=b}renderReport()};$('reportFrom').onchange=()=>{$('reportCyclePreset').value='custom';renderReport()};$('reportTo').onchange=()=>{$('reportCyclePreset').value='custom';renderReport()};$('printBtn').onclick=()=>{if(can('generate_pdf'))window.print()};$('exportCsvBtn').onclick=()=>{if(can('generate_pdf'))exportCSV()};
$('cycleType').onchange=updateCycleSettingsUI;$('anchorPayDate').onchange=updateCyclePreview;$('budgetCycleType').onchange=updateCyclePreview;$('budgetAnchorDate').onchange=updateCyclePreview;$('cycleForm').onsubmit=async e=>{e.preventDefault();const cycle_type=$('cycleType').value,anchor_pay_date=$('anchorPayDate').value||null,budget_cycle_type=$('budgetCycleType').value||'monthly',budget_anchor_date=$('budgetAnchorDate').value||null,o=owner();if(!(o.id===me.id||me.role==='admin'))return toast('No tienes permiso');if(cycle_type!=='variable'&&!anchor_pay_date)return toast('Selecciona una fecha de pago');if(cycle_type==='variable'&&!budget_anchor_date)return toast('Selecciona una fecha de referencia');const regular=cycle_type!=='variable',effective=regular?anchor_pay_date:budget_anchor_date,payload={owner_id:o.id,pay_day:regular?parseISODate(anchor_pay_date).getUTCDate():(ownerFinanceSetting().pay_day||15),cycle_type,anchor_pay_date:regular?anchor_pay_date:null,budget_cycle_type:regular?cycle_type:budget_cycle_type,budget_anchor_date:effective,business_mode:$('businessMode').checked,dashboard_sections:ownerFinanceSetting().dashboard_sections||{apartados:true,fijos:true,movimientos:true,metas:true}};const {error}=await sb.from('finance_settings').upsert(payload,{onConflict:'owner_id'});if(error)return apiError(error);await refreshData(false);setView('config');toast('Configuración actualizada')};
$('saveDashboardPrefsBtn').onclick=async()=>{const o=owner();if(!(o.id===me.id||me.role==='admin'))return toast('No tienes permiso');const dashboard_sections={apartados:$('dashShowApartados').checked,metas:$('dashShowMetas').checked,fijos:$('dashShowFijos').checked,movimientos:$('dashShowMovs').checked};const {error}=await sb.from('finance_settings').update({dashboard_sections}).eq('owner_id',o.id);if(error)return apiError(error);await refreshData(false);setView('config');toast('Preferencias guardadas')};
$('passwordForm').onsubmit=async e=>{e.preventDefault();const p=$('newPassword').value;if(p.length<8)return toast('Mínimo 8 caracteres');const {error}=await sb.auth.updateUser({password:p});if(error)return apiError(error);$('newPassword').value='';toast('Contraseña actualizada')};
(async()=>{const {data}=await sb.auth.getSession();session=data.session;if(session){currentOwnerId=session.user.id;try{await renderApp()}catch(e){apiError(e)}}if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});setInterval(()=>{if(session&&currentView==='dashboard'&&document.visibilityState==='visible')refreshData(false).catch(()=>{})},60000)})();
})();
