(()=>{
const SUPABASE_URL='https://cobuqvlfrufplefrkcgx.supabase.co';
const SUPABASE_KEY='sb_publishable_SKGz3p8xaze55as02_WVxA_P3KFoJO-';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>today().slice(0,8)+'01';
let session=null,me=null,myPerms={},currentOwnerId=null;
let profiles=[],permissions=[],shares=[],envelopes=[],accounts=[],ledger=[],fixedExpenses=[],cardPayments=[];
let tempPasswords={};
const PERMS=[
 ['add_envelope','Crear apartados'],['delete_envelope','Eliminar apartados'],['rename_envelope','Editar apartados'],
 ['modify_amounts','Registrar/modificar importes'],['view_movements','Ver movimientos'],['generate_pdf','Generar PDF'],
 ['share_finances','Compartir finanzas'],['manage_accounts','Administrar cuentas/tarjetas'],['manage_fixed_expenses','Administrar pagos fijos']
];
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),3600)}
function apiError(err,fallback='Ocurrió un error'){console.error(err);toast(err?.message||fallback)}
function profile(id){return profiles.find(x=>x.id===id)}
function can(p){return me?.role==='admin'||myPerms?.[p]===true}
function accessibleOwners(){if(me?.role==='admin')return profiles.filter(p=>p.active);const ids=new Set([me.id,...shares.filter(s=>s.user_id===me.id).map(s=>s.owner_id)]);return profiles.filter(p=>ids.has(p.id)&&p.active)}
function owner(){return profile(currentOwnerId)}
function canWriteOwner(id){if(id===me.id||me.role==='admin')return true;return shares.some(s=>s.owner_id===id&&s.user_id===me.id&&s.permission==='write')}
function own(list){return list.filter(x=>x.owner_id===currentOwnerId)}
function ownerAccounts(){return own(accounts).filter(a=>a.active)}
function ownerEnvelopes(){return own(envelopes).filter(e=>e.active)}
function ownerLedger(){return own(ledger)}
function ownerFixed(){return own(fixedExpenses).filter(f=>f.active)}
function ownerCardPayments(){return own(cardPayments)}
function accountBalance(a){
 const entries=ownerLedger().filter(e=>e.account_id===a.id);
 const paysOut=ownerCardPayments().filter(p=>p.source_account_id===a.id).reduce((s,p)=>s+Number(p.amount),0);
 const paysIn=ownerCardPayments().filter(p=>p.credit_account_id===a.id).reduce((s,p)=>s+Number(p.amount),0);
 if(a.account_type==='credit'){
  let debt=Number(a.opening_balance)||0;
  for(const e of entries){if(e.entry_type==='expense')debt+=Number(e.amount);else if(e.entry_type==='income')debt-=Number(e.amount);else debt+=Number(e.amount)*(Number(e.adjustment_direction)||1)}
  debt-=paysIn;return Math.max(0,debt);
 }
 let bal=Number(a.opening_balance)||0;
 for(const e of entries){if(e.entry_type==='income')bal+=Number(e.amount);else if(e.entry_type==='expense')bal-=Number(e.amount);else bal+=Number(e.amount)*(Number(e.adjustment_direction)||1)}
 bal-=paysOut;return bal;
}
function totalCash(){return ownerAccounts().filter(a=>a.account_type!=='credit').reduce((s,a)=>s+accountBalance(a),0)}
function totalDebt(){return ownerAccounts().filter(a=>a.account_type==='credit').reduce((s,a)=>s+accountBalance(a),0)}
function pendingFixedTotal(){return ownerFixed().reduce((s,f)=>s+Number(f.amount),0)}
function spentForEnvelope(eid,from=monthStart(),to=today()){return ownerLedger().filter(e=>e.entry_type==='expense'&&e.envelope_id===eid&&e.occurred_on>=from&&e.occurred_on<=to).reduce((s,e)=>s+Number(e.amount),0)}
function accountTypeLabel(t){return t==='credit'?'Crédito':t==='debit'?'Débito':'Efectivo'}
function frequencyLabel(f){return f==='weekly'?'Semanal':f==='biweekly'?'Quincenal':f==='monthly'?'Mensual':'Una vez'}
function nextDue(date,freq){const d=new Date(date+'T12:00:00Z');if(freq==='weekly')d.setUTCDate(d.getUTCDate()+7);else if(freq==='biweekly')d.setUTCDate(d.getUTCDate()+14);else if(freq==='monthly')d.setUTCMonth(d.getUTCMonth()+1);else return null;return d.toISOString().slice(0,10)}
async function loadAll(){
 const [p,up,s,e,a,l,f,cp]=await Promise.all([
  sb.from('profiles').select('*').order('full_name'),sb.from('user_permissions').select('*'),sb.from('shares').select('*').order('created_at'),
  sb.from('envelopes').select('*').order('created_at'),sb.from('accounts').select('*').order('created_at'),sb.from('ledger_entries').select('*').order('occurred_on',{ascending:false}),
  sb.from('fixed_expenses').select('*').order('next_due_date'),sb.from('card_payments').select('*').order('occurred_on',{ascending:false})
 ]);
 for(const r of [p,up,s,e,a,f])if(r.error)throw r.error;
 profiles=p.data||[];permissions=up.data||[];shares=s.data||[];envelopes=e.data||[];accounts=a.data||[];fixedExpenses=f.data||[];ledger=l.error?[]:(l.data||[]);cardPayments=cp.error?[]:(cp.data||[]);
 me=profile(session.user.id);myPerms=permissions.find(x=>x.user_id===session.user.id)||{};if(!me||!me.active)throw new Error('Usuario inactivo o sin perfil');if(!currentOwnerId||!accessibleOwners().some(x=>x.id===currentOwnerId))currentOwnerId=me.id;
}
function refreshOwnerSelector(){const opts=accessibleOwners();$('ownerSelector').innerHTML=opts.map(o=>`<option value="${o.id}">${safe(o.full_name)}${me?.role==='admin'&&o.id!==me.id?' · '+safe(o.username):''}</option>`).join('');$('ownerSelector').value=currentOwnerId}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('view-'+name).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='dashboard')renderDashboard();if(name==='movimientos')renderMovements();if(name==='apartados')renderEnvelopes();if(name==='cuentas')renderAccounts();if(name==='fijos')renderFixed();if(name==='compartir')renderShares();if(name==='usuarios')renderUsers();if(name==='reporte')renderReport()}
async function refresh(view){await loadAll();refreshOwnerSelector();setView(view)}
function movementCard(t){const a=accounts.find(x=>x.id===t.account_id),e=envelopes.find(x=>x.id===t.envelope_id);const label=t.entry_type==='income'?'Ingreso':t.entry_type==='expense'?'Gasto':'Ajuste';const cls=t.entry_type==='income'?'good':t.entry_type==='expense'?'bad':'warn';const credit=a?.account_type==='credit'&&t.entry_type==='expense';return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(t.comment||label)}</div><div class="small muted">${safe(t.occurred_on)} · ${safe(a?.name||'Cuenta')}${e?' · '+safe(e.name):''}</div></div><div class="right"><div class="amount ${cls}">${money(t.amount)}</div><span class="pill ${cls}">${credit?'Compra crédito':label}</span></div></div></div>`}
function fixedCard(f,withActions=true){const due=f.next_due_date,late=due<today(),e=envelopes.find(x=>x.id===f.envelope_id),a=accounts.find(x=>x.id===f.preferred_account_id);return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(f.name)}</div><div class="small muted">${frequencyLabel(f.frequency)} · vence ${safe(due)}${e?' · '+safe(e.name):''}${a?' · '+safe(a.name):''}</div></div><div class="right"><div class="amount ${late?'bad':''}">${money(f.amount)}</div><span class="pill ${late?'bad':'warn'}">${late?'Vencido':'Pendiente'}</span></div></div>${withActions?`<div class="row" style="margin-top:9px"><button class="btn primary pay-fixed" data-id="${f.id}">Pagar</button><button class="btn secondary edit-fixed" data-id="${f.id}">Editar</button><button class="btn ghost toggle-fixed" data-id="${f.id}">Desactivar</button></div>`:''}</div>`}
function renderDashboard(){
 refreshOwnerSelector();const o=owner();if(!o)return;$('dashOwnerName').textContent=o.full_name;
 if(me.role==='admin'&&o.id!==me.id){$('adminModeNote').textContent=`Modo administrador: estás viendo y puedes modificar las finanzas de ${o.full_name} (${o.username}).`;$('adminModeNote').classList.remove('hidden')}else{$('adminModeNote').classList.add('hidden')}
 if(!can('view_movements')){$('dashCash').textContent='Sin permiso';$('recentList').innerHTML='<div class="note">No tienes permiso para ver movimientos.</div>';return}
 $('dashCash').textContent=money(totalCash());$('statCreditDebt').textContent=money(totalDebt());$('statFixed').textContent=money(pendingFixedTotal());const tx=ownerLedger(),ms=monthStart(),td=today();$('statIncome').textContent=money(tx.filter(x=>x.entry_type==='income'&&x.occurred_on>=ms&&x.occurred_on<=td).reduce((s,x)=>s+Number(x.amount),0));$('statExpense').textContent=money(tx.filter(x=>x.entry_type==='expense'&&x.occurred_on>=ms&&x.occurred_on<=td).reduce((s,x)=>s+Number(x.amount),0));
 const env=ownerEnvelopes();$('dashBars').innerHTML=env.length?env.map(e=>{const spent=spentForEnvelope(e.id),budget=Number(e.monthly_budget)||0,pct=budget?Math.min(100,spent/budget*100):0;return `<div class="barrow"><span>${safe(e.name)}</span><div class="bar"><span style="width:${pct}%"></span></div><b>${budget?money(spent)+' / '+money(budget):money(spent)}</b></div>`}).join(''):'<div class="empty">Aún no hay apartados.</div>';
 const f=[...ownerFixed()].sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date)).slice(0,5);$('dashFixed').innerHTML=f.length?f.map(x=>fixedCard(x,false)).join(''):'<div class="empty">No hay pagos fijos pendientes.</div>';const recent=[...ownerLedger()].sort((a,b)=>(b.occurred_on+b.created_at).localeCompare(a.occurred_on+a.created_at)).slice(0,6);$('recentList').innerHTML=recent.length?recent.map(movementCard).join(''):'<div class="empty">No hay movimientos todavía.</div>';
}
function renderMovements(){const write=canWriteOwner(currentOwnerId)&&can('modify_amounts');$('newIncomeBtn').disabled=!write;$('newExpenseBtn').disabled=!write;const from=$('filterFrom').value,to=$('filterTo').value;let tx=[...ownerLedger()].sort((a,b)=>(b.occurred_on+b.created_at).localeCompare(a.occurred_on+a.created_at));if(from)tx=tx.filter(x=>x.occurred_on>=from);if(to)tx=tx.filter(x=>x.occurred_on<=to);$('movementList').innerHTML=!can('view_movements')?'<div class="note">No tienes permiso para visualizar movimientos.</div>':(tx.length?tx.map(movementCard).join(''):'<div class="empty">No hay movimientos.</div>')}
function fillMovementAccounts(){const type=$('movementType').value;const list=ownerAccounts().filter(a=>type==='income'?a.account_type!=='credit':true);$('movementAccount').innerHTML=list.map(a=>`<option value="${a.id}">${safe(a.name)} · ${accountTypeLabel(a.account_type)}</option>`).join('');$('movementEnvelope').innerHTML='<option value="">Sin apartado</option>'+ownerEnvelopes().map(e=>`<option value="${e.id}">${safe(e.name)}</option>`).join('');$('movementEnvelopeField').classList.toggle('hidden',type==='income')}
function openMovement(type,fixed=null){if(!canWriteOwner(currentOwnerId)||!can('modify_amounts'))return toast('No tienes permiso para registrar movimientos');$('movementType').value=type;$('movementDate').value=today();$('movementAmount').value=fixed?fixed.amount:'';$('movementComment').value=fixed?fixed.name:'';$('movementFixedId').value=fixed?.id||'';$('movementFormTitle').textContent=fixed?'Pagar '+fixed.name:(type==='income'?'Registrar ingreso':'Registrar gasto');fillMovementAccounts();if(fixed){if(fixed.preferred_account_id&&ownerAccounts().some(a=>a.id===fixed.preferred_account_id))$('movementAccount').value=fixed.preferred_account_id;$('movementEnvelope').value=fixed.envelope_id||''}$('movementFormCard').classList.remove('hidden');setView('movimientos');window.scrollTo({top:0,behavior:'smooth'})}
function renderEnvelopes(){
 const write=canWriteOwner(currentOwnerId);$('newEnvelopeBtn').disabled=!(write&&can('add_envelope'));const list=ownerEnvelopes();
 $('envelopeList').innerHTML=list.length?list.map(e=>{const spent=spentForEnvelope(e.id),budget=Number(e.monthly_budget)||0,remain=budget-spent;return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(e.name)}</div><div class="small muted">${budget?'Presupuesto '+money(budget):'Sin presupuesto mensual'}</div></div><div class="right"><div class="amount ${remain<0?'bad':''}">${budget?money(Math.max(0,remain)):'—'}</div><div class="small muted">${budget?'Disponible del presupuesto':'Gastado '+money(spent)}</div></div></div><div class="row" style="margin-top:9px"><button class="btn secondary edit-env" data-id="${e.id}" ${!(write&&can('rename_envelope'))?'disabled':''}>Editar</button><button class="btn danger del-env" data-id="${e.id}" ${!(write&&can('delete_envelope'))?'disabled':''}>Eliminar</button></div></div>`}).join(''):'<div class="empty">No hay apartados.</div>';
 document.querySelectorAll('.edit-env').forEach(b=>b.onclick=()=>editEnvelope(b.dataset.id));document.querySelectorAll('.del-env').forEach(b=>b.onclick=()=>deleteEnvelope(b.dataset.id));
 const debts=own(accounts).filter(a=>a.account_type==='credit'&&a.active);
 $('envelopeDebtList').innerHTML=debts.length?debts.map(a=>`<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(a.name)}</div><div class="small muted">Deuda inicial ${money(a.opening_balance)}${a.opening_note?' · '+safe(a.opening_note):' · Sin motivo registrado'}</div></div><div class="right"><div class="amount warn">Debes ${money(accountBalance(a))}</div><div class="small muted">Límite ${money(a.credit_limit)}</div></div></div><div class="row" style="margin-top:9px"><button class="btn secondary edit-debt-account" data-id="${a.id}" ${!(write&&can('manage_accounts'))?'disabled':''}>Editar deuda / tarjeta</button></div></div>`).join(''):'<div class="empty">No hay tarjetas de crédito activas.</div>';
 document.querySelectorAll('.edit-debt-account').forEach(b=>b.onclick=()=>{setView('cuentas');editAccount(b.dataset.id)});
}
function editEnvelope(id){const e=envelopes.find(x=>x.id===id);if(!e)return;$('envelopeId').value=e.id;$('envelopeName').value=e.name;$('envelopeBudget').value=e.monthly_budget||0;$('envelopeFormTitle').textContent='Editar apartado';$('envelopeFormCard').classList.remove('hidden')}
async function deleteEnvelope(id){if(!confirm('¿Eliminar este apartado? Los movimientos nuevos conservarán el historial pero quedarán sin categoría.'))return;const {error}=await sb.from('envelopes').delete().eq('id',id);if(error)return apiError(error);await refresh('apartados');toast('Apartado eliminado')}
function renderAccounts(){
 $('newAccountBtn').disabled=!(canWriteOwner(currentOwnerId)&&can('manage_accounts'));const list=own(accounts);
 $('accountList').innerHTML=list.length?list.map(a=>{const v=accountBalance(a),credit=a.account_type==='credit',avail=credit?Math.max(0,Number(a.credit_limit)-v):null;return `<div class="item"><div class="row between"><div class="grow"><div class="item-title">${safe(a.name)}</div><div class="small muted">${accountTypeLabel(a.account_type)}${credit?` · Deuda inicial ${money(a.opening_balance)}`:` · Saldo inicial ${money(a.opening_balance)}`}</div>${a.opening_note?`<div class="small muted">${safe(a.opening_note)}</div>`:(credit?'<div class="small muted">Sin motivo de deuda inicial registrado</div>':'')}</div><div class="right"><div class="amount ${credit?'warn':v<0?'bad':'good'}">${credit?'Debes '+money(v):money(v)}</div>${credit?`<div class="small muted">Disponible crédito ${money(avail)}</div>`:''}</div></div><div class="row" style="margin-top:9px"><span class="pill ${a.active?'good':'bad'}">${a.active?'Activa':'Inactiva'}</span><button class="btn secondary edit-account" data-id="${a.id}" ${!can('manage_accounts')?'disabled':''}>Editar</button>${credit&&a.active?`<button class="btn blue pay-card" data-id="${a.id}">Pagar tarjeta</button>`:''}<button class="btn ghost toggle-account" data-id="${a.id}" ${!can('manage_accounts')?'disabled':''}>${a.active?'Desactivar':'Activar'}</button></div></div>`}).join(''):'<div class="empty">No hay cuentas ni tarjetas.</div>';
 document.querySelectorAll('.edit-account').forEach(b=>b.onclick=()=>editAccount(b.dataset.id));document.querySelectorAll('.pay-card').forEach(b=>b.onclick=()=>openCardPayment(b.dataset.id));document.querySelectorAll('.toggle-account').forEach(b=>b.onclick=()=>toggleAccount(b.dataset.id));
}
function accountHasActivity(id){return ledger.some(x=>x.account_id===id)||cardPayments.some(x=>x.source_account_id===id||x.credit_account_id===id)}
function openAccountCreate(){$('accountId').value='';$('accountName').value='';$('accountType').value='debit';$('accountOpening').value='0';$('accountLimit').value='0';$('accountOpeningNote').value='';$('accountFormTitle').textContent='Nueva cuenta / tarjeta';$('accountType').disabled=false;$('accountTypeHint').textContent='';accountTypeUI();$('accountFormCard').classList.remove('hidden')}
function editAccount(id){const a=accounts.find(x=>x.id===id);if(!a)return;$('accountId').value=a.id;$('accountName').value=a.name;$('accountType').value=a.account_type;$('accountOpening').value=a.opening_balance||0;$('accountLimit').value=a.credit_limit||0;$('accountOpeningNote').value=a.opening_note||'';$('accountFormTitle').textContent='Editar cuenta / tarjeta';const locked=accountHasActivity(a.id);$('accountType').disabled=locked;$('accountTypeHint').textContent=locked?'El tipo no puede cambiarse porque esta cuenta ya tiene movimientos o pagos.':'Puedes cambiar el tipo porque todavía no tiene movimientos.';accountTypeUI();$('accountFormCard').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function toggleAccount(id){const a=accounts.find(x=>x.id===id);if(!a)return;const {error}=await sb.from('accounts').update({active:!a.active}).eq('id',id);if(error)return apiError(error);await refresh('cuentas');toast('Cuenta actualizada')}
function openCardPayment(id){const a=accounts.find(x=>x.id===id);if(!a)return;const sources=ownerAccounts().filter(x=>x.account_type!=='credit'&&x.id!==id);if(!sources.length)return toast('Necesitas una cuenta de débito o efectivo para pagar la tarjeta');$('paymentCreditId').value=id;$('paymentCreditName').value=a.name;$('paymentSource').innerHTML=sources.map(x=>`<option value="${x.id}">${safe(x.name)} · ${money(accountBalance(x))}</option>`).join('');$('paymentAmount').value='';$('paymentDate').value=today();$('paymentComment').value='';$('paymentFormCard').classList.remove('hidden')}
function accountTypeUI(){const credit=$('accountType').value==='credit';$('creditLimitField').classList.toggle('hidden',!credit);$('openingLabel').textContent=credit?'Deuda inicial':'Saldo inicial';$('openingNoteLabel').textContent=credit?'Motivo / detalle de la deuda inicial':'Nota del saldo inicial';$('accountOpeningNote').placeholder=credit?'Ej. Compra anterior, saldo transferido, deuda previa al empezar a usar Mi Dinero':'Ej. Saldo que ya tenía la cuenta al empezar a usar Mi Dinero'}
function renderFixed(){
 $('newFixedBtn').disabled=!(canWriteOwner(currentOwnerId)&&can('manage_fixed_expenses'));const list=[...own(fixedExpenses)].sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date));$('fixedList').innerHTML=list.length?list.map(f=>f.active?fixedCard(f,true):`<div class="item"><div class="row between"><div><div class="item-title">${safe(f.name)}</div><div class="small muted">Inactivo</div></div><button class="btn ghost toggle-fixed" data-id="${f.id}">Activar</button></div></div>`).join(''):'<div class="empty">No hay pagos fijos.</div>';document.querySelectorAll('.pay-fixed').forEach(b=>b.onclick=()=>{const f=fixedExpenses.find(x=>x.id===b.dataset.id);openMovement('expense',f)});document.querySelectorAll('.edit-fixed').forEach(b=>b.onclick=()=>editFixed(b.dataset.id));document.querySelectorAll('.toggle-fixed').forEach(b=>b.onclick=()=>toggleFixed(b.dataset.id));
}
function fillFixedSelectors(){$('fixedEnvelope').innerHTML='<option value="">Sin apartado</option>'+ownerEnvelopes().map(e=>`<option value="${e.id}">${safe(e.name)}</option>`).join('');$('fixedAccount').innerHTML='<option value="">Elegir al pagar</option>'+ownerAccounts().map(a=>`<option value="${a.id}">${safe(a.name)} · ${accountTypeLabel(a.account_type)}</option>`).join('')}
function editFixed(id){const f=fixedExpenses.find(x=>x.id===id);if(!f)return;fillFixedSelectors();$('fixedId').value=f.id;$('fixedName').value=f.name;$('fixedAmount').value=f.amount;$('fixedFrequency').value=f.frequency;$('fixedDue').value=f.next_due_date;$('fixedEnvelope').value=f.envelope_id||'';$('fixedAccount').value=f.preferred_account_id||'';$('fixedFormTitle').textContent='Editar pago fijo';$('fixedFormCard').classList.remove('hidden')}
async function toggleFixed(id){const f=fixedExpenses.find(x=>x.id===id);if(!f)return;const {error}=await sb.from('fixed_expenses').update({active:!f.active}).eq('id',id);if(error)return apiError(error);await refresh('fijos')}
function renderShares(){const others=profiles.filter(u=>u.active&&u.id!==me.id);$('shareUser').innerHTML=others.map(u=>`<option value="${u.id}">${safe(u.full_name)} (${safe(u.username)})</option>`).join('');$('shareForm').querySelector('button').disabled=!can('share_finances')||currentOwnerId!==me.id;const mine=shares.filter(s=>s.owner_id===me.id);$('shareList').innerHTML=mine.length?mine.map(s=>{const u=profile(s.user_id);return `<div class="item"><div class="row between"><div><div class="item-title">${safe(u?.full_name||'Usuario')}</div><div class="small muted">${safe(u?.username||'')}</div></div><span class="pill ${s.permission==='write'?'blue':''}">${s.permission==='write'?'Lectura y escritura':'Solo lectura'}</span></div><button class="btn danger revoke-share" data-id="${s.id}" style="margin-top:9px">Quitar acceso</button></div>`}).join(''):'<div class="empty">No has compartido tus finanzas.</div>';document.querySelectorAll('.revoke-share').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('shares').delete().eq('id',b.dataset.id);if(error)return apiError(error);await refresh('compartir')})}
function renderPermissionChecks(){$('permissionChecks').innerHTML=PERMS.map(([k,l])=>`<label style="display:flex;gap:8px;align-items:center;font-weight:600"><input type="checkbox" data-perm="${k}" style="width:auto;min-height:auto" checked> ${l}</label>`).join('')}
async function refreshUsersDirectory(show=false){const [p,up]=await Promise.all([sb.from('profiles').select('*').order('created_at'),sb.from('user_permissions').select('*')]);if(p.error)throw p.error;if(up.error)throw up.error;profiles=p.data||[];permissions=up.data||[];me=profile(session.user.id);myPerms=permissions.find(x=>x.user_id===me.id)||{};refreshOwnerSelector();renderUsers();if(show)toast('Usuarios actualizados')}
function renderUsers(){if(me.role!=='admin')return;$('userList').innerHTML=profiles.map(u=>{const visible=tempPasswords[u.id];return `<div class="item"><div class="row between"><div><div class="item-title">${safe(u.full_name)}</div><div class="small muted">${u.role==='admin'?'Administrador':'Usuario'} · ${safe(u.username)}</div></div><span class="pill ${u.active?'good':'bad'}">${u.active?'Activo':'Inactivo'}</span></div><div class="credential-box"><div class="credential-line"><span>Usuario</span><code>${safe(u.username)}</code></div><div class="credential-line"><span>Contraseña</span>${visible?`<code>${safe(visible)}</code>`:'<span class="protected">Protegida por Supabase</span>'}</div></div><div class="row" style="margin-top:9px">${u.active?`<button class="btn primary view-user-finances" data-id="${u.id}">Ver / administrar finanzas</button>`:''}${u.id!==me.id?`<button class="btn secondary toggle-user" data-id="${u.id}">${u.active?'Desactivar':'Activar'}</button><button class="btn ghost perms-user" data-id="${u.id}">Permisos</button><button class="btn ghost reset-pass" data-id="${u.id}">Nueva contraseña</button>`:'<span class="small muted">Tu contraseña se cambia en Ajustes.</span>'}</div></div>`}).join('');document.querySelectorAll('.view-user-finances').forEach(b=>b.onclick=()=>{currentOwnerId=b.dataset.id;refreshOwnerSelector();setView('dashboard');toast('Ahora administras las finanzas de '+(profile(b.dataset.id)?.full_name||'este usuario'))});document.querySelectorAll('.toggle-user').forEach(b=>b.onclick=async()=>{const u=profile(b.dataset.id);const {error}=await sb.from('profiles').update({active:!u.active}).eq('id',u.id);if(error)return apiError(error);await refreshUsersDirectory()});document.querySelectorAll('.perms-user').forEach(b=>b.onclick=()=>editPermissions(b.dataset.id));document.querySelectorAll('.reset-pass').forEach(b=>b.onclick=()=>resetPassword(b.dataset.id))}
async function editPermissions(id){const u=profile(id),p=permissions.find(x=>x.user_id===id)||{};if(!u)return;const current=PERMS.map(([k,l])=>`${l}: ${p[k]?'Sí':'No'}`).join('\n');const choice=prompt(`Permisos actuales de ${u.full_name}:\n\n${current}\n\nEscribe TODO para habilitar todos o NINGUNO para deshabilitar todos.`);if(choice===null)return;const v=choice.trim().toUpperCase();if(!['TODO','NINGUNO'].includes(v))return toast('Sin cambios');const update=Object.fromEntries(PERMS.map(([k])=>[k,v==='TODO']));const {error}=await sb.from('user_permissions').update(update).eq('user_id',id);if(error)return apiError(error);await refreshUsersDirectory();toast('Permisos actualizados')}
function makeTempPassword(){const b=new Uint32Array(2);crypto.getRandomValues(b);return `MiDinero-${b[0].toString(36)}${b[1].toString(36)}`.slice(0,20)}
async function resetPassword(id){const u=profile(id),suggested=makeTempPassword(),password=prompt(`Nueva contraseña temporal para ${u.full_name}:`,suggested);if(password===null)return;if(password.length<8)return toast('Mínimo 8 caracteres');const {data,error}=await sb.functions.invoke('reset-user-password',{body:{user_id:id,password}});if(error)return apiError(error);if(data?.error)return toast(data.error);tempPasswords[id]=password;renderUsers();toast('Contraseña temporal actualizada')}
function renderReport(){if(!$('reportFrom').value)$('reportFrom').value=monthStart();if(!$('reportTo').value)$('reportTo').value=today();const from=$('reportFrom').value,to=$('reportTo').value;const tx=ownerLedger().filter(x=>(!from||x.occurred_on>=from)&&(!to||x.occurred_on<=to)).sort((a,b)=>a.occurred_on.localeCompare(b.occurred_on));const pays=ownerCardPayments().filter(x=>(!from||x.occurred_on>=from)&&(!to||x.occurred_on<=to));$('reportIncome').textContent=money(tx.filter(x=>x.entry_type==='income').reduce((s,x)=>s+Number(x.amount),0));$('reportExpense').textContent=money(tx.filter(x=>x.entry_type==='expense').reduce((s,x)=>s+Number(x.amount),0));$('reportCardPayments').textContent=money(pays.reduce((s,x)=>s+Number(x.amount),0));$('reportDebt').textContent=money(totalDebt());$('printBtn').disabled=!can('generate_pdf');const rows=[...tx.map(t=>({date:t.occurred_on,type:t.entry_type==='income'?'Ingreso':t.entry_type==='expense'?'Gasto':'Ajuste',account:accounts.find(a=>a.id===t.account_id)?.name||'',env:envelopes.find(e=>e.id===t.envelope_id)?.name||'',amount:t.amount,comment:t.comment||''})),...pays.map(p=>({date:p.occurred_on,type:'Pago tarjeta',account:(accounts.find(a=>a.id===p.source_account_id)?.name||'')+' → '+(accounts.find(a=>a.id===p.credit_account_id)?.name||''),env:'',amount:p.amount,comment:p.comment||''}))].sort((a,b)=>a.date.localeCompare(b.date));$('reportBody').innerHTML=rows.map(r=>`<tr><td>${safe(r.date)}</td><td>${safe(r.type)}</td><td>${safe(r.account)}</td><td>${safe(r.env)}</td><td>${money(r.amount)}</td><td>${safe(r.comment)}</td></tr>`).join('')||'<tr><td colspan="6">Sin movimientos.</td></tr>'}
async function renderApp(){await loadAll();$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('whoName').textContent=me.full_name;$('whoRole').textContent=me.role==='admin'?'Administrador':'Usuario';refreshOwnerSelector();renderPermissionChecks();const navInner=document.querySelector('.nav-inner');if(me.role==='admin'&&!document.querySelector('[data-view="usuarios"]')){const b=document.createElement('button');b.dataset.view='usuarios';b.innerHTML='<span class="ico">♟</span>Usuarios';b.onclick=()=>setView('usuarios');navInner.insertBefore(b,navInner.lastElementChild)}setView('dashboard')}
$('loginForm').onsubmit=async e=>{e.preventDefault();const username=$('loginUser').value.trim().toLowerCase(),password=$('loginPass').value;if(!/^[a-z0-9._-]{3,32}$/.test(username))return toast('Usuario inválido');const res=await sb.auth.signInWithPassword({email:username+'@midinero.local',password});if(res.error)return apiError(res.error,'Usuario o contraseña incorrectos');session=res.data.session;currentOwnerId=session.user.id;try{await renderApp()}catch(err){apiError(err)}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('ownerSelector').onchange=()=>{currentOwnerId=$('ownerSelector').value;setView('dashboard')};
$('quickIncome').onclick=()=>openMovement('income');$('quickExpense').onclick=()=>openMovement('expense');$('quickAccount').onclick=()=>{setView('cuentas');openAccountCreate()};$('quickFixed').onclick=()=>{setView('fijos');fillFixedSelectors();$('fixedId').value='';$('fixedName').value='';$('fixedAmount').value='';$('fixedDue').value=today();$('fixedFormCard').classList.remove('hidden')};
$('newIncomeBtn').onclick=()=>openMovement('income');$('newExpenseBtn').onclick=()=>openMovement('expense');$('cancelMovementBtn').onclick=()=>$('movementFormCard').classList.add('hidden');$('movementType').onchange=fillMovementAccounts;
$('movementForm').onsubmit=async e=>{e.preventDefault();const type=$('movementType').value,accountId=$('movementAccount').value,amount=Number($('movementAmount').value),fixedId=$('movementFixedId').value||null;if(!(amount>0)||!accountId)return toast('Completa monto y cuenta');const payload={owner_id:currentOwnerId,account_id:accountId,envelope_id:type==='expense'?($('movementEnvelope').value||null):null,fixed_expense_id:fixedId,created_by:me.id,entry_type:type,amount,comment:$('movementComment').value.trim(),occurred_on:$('movementDate').value||today(),adjustment_direction:null};const {error}=await sb.from('ledger_entries').insert(payload);if(error)return apiError(error);if(fixedId){const f=fixedExpenses.find(x=>x.id===fixedId),n=nextDue(payload.occurred_on,f.frequency);const update={last_paid_on:payload.occurred_on};if(n)update.next_due_date=n;else update.active=false;await sb.from('fixed_expenses').update(update).eq('id',fixedId)}$('movementFormCard').classList.add('hidden');await refresh('movimientos');toast(type==='income'?'Ingreso registrado':'Gasto registrado')};
$('filterFrom').onchange=renderMovements;$('filterTo').onchange=renderMovements;
$('newEnvelopeBtn').onclick=()=>{$('envelopeId').value='';$('envelopeName').value='';$('envelopeBudget').value='0';$('envelopeFormTitle').textContent='Nuevo apartado';$('envelopeFormCard').classList.remove('hidden')};$('cancelEnvelopeBtn').onclick=()=>$('envelopeFormCard').classList.add('hidden');
$('envelopeForm').onsubmit=async e=>{e.preventDefault();const id=$('envelopeId').value,name=$('envelopeName').value.trim(),budget=Math.max(0,Number($('envelopeBudget').value)||0);if(!name)return;let r=id?await sb.from('envelopes').update({name,monthly_budget:budget}).eq('id',id):await sb.from('envelopes').insert({owner_id:currentOwnerId,name,monthly_budget:budget,initial_balance:0,current_balance:0});if(r.error)return apiError(r.error);$('envelopeFormCard').classList.add('hidden');await refresh('apartados');toast('Apartado guardado')};
$('newAccountBtn').onclick=openAccountCreate;$('cancelAccountBtn').onclick=()=>{$('accountFormCard').classList.add('hidden');$('accountType').disabled=false};$('accountType').onchange=accountTypeUI;
$('accountForm').onsubmit=async e=>{e.preventDefault();const id=$('accountId').value,name=$('accountName').value.trim(),existing=id?accounts.find(x=>x.id===id):null,type=$('accountType').disabled&&existing?existing.account_type:$('accountType').value,opening=Math.max(0,Number($('accountOpening').value)||0),limit=Math.max(0,Number($('accountLimit').value)||0),opening_note=$('accountOpeningNote').value.trim();if(!name)return;const payload={owner_id:currentOwnerId,name,account_type:type,opening_balance:opening,credit_limit:type==='credit'?limit:null,opening_note};const r=id?await sb.from('accounts').update(payload).eq('id',id):await sb.from('accounts').insert(payload);if(r.error)return apiError(r.error);$('accountFormCard').classList.add('hidden');$('accountType').disabled=false;await refresh('cuentas');toast(id?'Cuenta actualizada':'Cuenta agregada')};
$('cancelPaymentBtn').onclick=()=>$('paymentFormCard').classList.add('hidden');
$('paymentForm').onsubmit=async e=>{e.preventDefault();const amount=Number($('paymentAmount').value),creditId=$('paymentCreditId').value,source=$('paymentSource').value;if(!(amount>0)||!source||!creditId)return;const {error}=await sb.from('card_payments').insert({owner_id:currentOwnerId,source_account_id:source,credit_account_id:creditId,created_by:me.id,amount,comment:$('paymentComment').value.trim(),occurred_on:$('paymentDate').value||today()});if(error)return apiError(error);$('paymentFormCard').classList.add('hidden');await refresh('cuentas');toast('Pago a tarjeta registrado')};
$('newFixedBtn').onclick=()=>{fillFixedSelectors();$('fixedId').value='';$('fixedName').value='';$('fixedAmount').value='';$('fixedFrequency').value='monthly';$('fixedDue').value=today();$('fixedEnvelope').value='';$('fixedAccount').value='';$('fixedFormTitle').textContent='Nuevo pago fijo';$('fixedFormCard').classList.remove('hidden')};$('cancelFixedBtn').onclick=()=>$('fixedFormCard').classList.add('hidden');
$('fixedForm').onsubmit=async e=>{e.preventDefault();const id=$('fixedId').value,payload={owner_id:currentOwnerId,name:$('fixedName').value.trim(),amount:Number($('fixedAmount').value),frequency:$('fixedFrequency').value,next_due_date:$('fixedDue').value,envelope_id:$('fixedEnvelope').value||null,preferred_account_id:$('fixedAccount').value||null,active:true};if(!payload.name||!(payload.amount>0)||!payload.next_due_date)return toast('Completa los datos');const r=id?await sb.from('fixed_expenses').update(payload).eq('id',id):await sb.from('fixed_expenses').insert(payload);if(r.error)return apiError(r.error);$('fixedFormCard').classList.add('hidden');await refresh('fijos');toast('Pago fijo guardado')};
$('shareForm').onsubmit=async e=>{e.preventDefault();const userId=$('shareUser').value;if(!userId)return;const permission=$('sharePermission').value,existing=shares.find(s=>s.owner_id===me.id&&s.user_id===userId);const r=existing?await sb.from('shares').update({permission}).eq('id',existing.id):await sb.from('shares').insert({owner_id:me.id,user_id:userId,permission});if(r.error)return apiError(r.error);await refresh('compartir');toast('Finanzas compartidas')};
$('refreshUsersBtn').onclick=()=>refreshUsersDirectory(true).catch(apiError);$('newUserBtn').onclick=()=>$('userFormCard').classList.remove('hidden');$('cancelUserBtn').onclick=()=>$('userFormCard').classList.add('hidden');
$('userForm').onsubmit=async e=>{e.preventDefault();const username=$('userUsername').value.trim().toLowerCase(),password=$('userPassword').value,full_name=$('userFullname').value.trim(),role=$('userRole').value;if(!/^[a-z0-9._-]{3,32}$/.test(username))return toast('Usuario inválido');if(password.length<8)return toast('Mínimo 8 caracteres');const perms={};document.querySelectorAll('[data-perm]').forEach(c=>perms[c.dataset.perm]=c.checked);const {data,error}=await sb.functions.invoke('create-user',{body:{username,password,full_name,permissions:perms}});if(error)return apiError(error);const id=data?.user_id;if(id){tempPasswords[id]=password;await sb.from('profiles').update({role}).eq('id',id);await sb.from('user_permissions').update(perms).eq('user_id',id)}$('userForm').reset();renderPermissionChecks();$('userFormCard').classList.add('hidden');await refreshUsersDirectory();renderUsers();toast('Usuario creado')};
$('reportFrom').onchange=renderReport;$('reportTo').onchange=renderReport;$('printBtn').onclick=()=>{if(can('generate_pdf'))window.print()};
$('passwordForm').onsubmit=async e=>{e.preventDefault();const p=$('newPassword').value;if(p.length<8)return toast('Mínimo 8 caracteres');const {error}=await sb.auth.updateUser({password:p});if(error)return apiError(error);$('newPassword').value='';toast('Contraseña actualizada')};
(async()=>{const {data}=await sb.auth.getSession();session=data.session;if(session){currentOwnerId=session.user.id;try{await renderApp()}catch(e){apiError(e)}}if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{})})();
})();
